'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),guide=require('../dist/disney-guide.js'),park=JSON.parse(fs.readFileSync(__dirname+'/../dist/park-data.json'));
const source=fs.readFileSync(__dirname+'/../dist/app.js','utf8'),ctx={DisneyGuide:guide,esc:s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;')};vm.createContext(require('./helpers/near-park.cjs')(ctx));vm.runInContext(source.slice(source.indexOf('function ageData('),source.indexOf('function childBadge(')),ctx);
const ride=slug=>park.rides.find(r=>r.officialUrl?.endsWith('/'+slug)),big=ride('big-thunder-mountain'),pan=ride('peter-pans-flight'),slinky=ride('slinky-dog-zigzag-spin'),tower=ride('twilight-zone-tower-of-terror');
for(const r of park.rides){const entry=guide.get(r.id);assert(entry.ageGroups.length,'source ages missing: '+r.name);assert.equal(new URL(entry.ageSourceUrl).hostname,'www.disneylandparis.com');assert(ctx.ageBadge(r).includes('Disney:'));if(entry.ageRecommendation){assert.equal(new URL(entry.ageRecommendation.sourceUrl).hostname,'www.sortiraparis.com');assert(ctx.ageBadge(r,true).includes('keine Einlassregel'));}}
assert(guide.get(ride('its-a-small-world').id).ageGroups.includes('All Ages'),'Catalogue -app alias retains All Ages classification');assert(!ctx.ageMatches(big,'Preschoolers'));assert(ctx.ageMatches(big,'Kids'));assert(ctx.ageMatches(pan,'Preschoolers'));assert(ctx.ageMatches(pan,'Adults'),'All Ages matches adult filter');assert(ctx.ageMatches(slinky,'From the age of 1 year'));assert(ctx.ageBadge(slinky).includes('Ab 1 Jahr'));assert(ctx.ageBadge(pan).includes('3–5 Jahre'));assert(ctx.ageBadge(big).includes('ab 6 Jahren'));assert(!ctx.ageBadge(tower).includes('Kindertipp'),'height/intensity must never invent an age');assert(!ctx.ageMatches({id:'missing'},'Kids'),'unknown age does not match');assert(ctx.ageMatches({id:'missing'},'all'));assert.equal(ctx.ageBadge({id:'wc-1',category:'toilet'}),'');
// Exercise the real list with an age filter; clearing restores the same available targets.
const els=new Map();ctx.$=id=>{if(!els.has(id))els.set(id,{value:'all',checked:true,setAttribute(){}});return els.get(id);};Object.assign(ctx,{data:{rides:[big,pan,tower]},renderHiddenTargets(){},uninterested:new Set(),parkMatches:()=>true,rideSearchText:r=>r.name.toLowerCase(),onlyFav:false,favorites:new Set(),visited:new Set(),ratingsMode:false,rideDistances:()=>new Map(),sortRides:r=>r,Date,DisneyRatings:{get:()=>null},esc:ctx.esc,selectedPark:'all',nextShowBadge:()=>'',targetAvailable:()=>true,waitBadge:()=>'',childBadge:()=>'',activeHomeView:'all',originLabel:'Eingang',remaining:()=>[],planning:false});ctx.$('search').value='';ctx.$('age-group').value='Preschoolers';vm.runInContext('let lastRideDistancePaint=0;'+source.slice(source.indexOf('function renderRides('),source.indexOf("$('rides-list').addEventListener('click',async")),ctx);ctx.renderRides();assert(ctx.$('rides-list').innerHTML.includes(pan.name));assert(!ctx.$('rides-list').innerHTML.includes(big.name));assert(!ctx.$('rides-list').innerHTML.includes(tower.name));assert.equal(ctx.$('filter-count').textContent,'1');ctx.$('age-group').value='all';ctx.renderRides();assert(ctx.$('rides-list').innerHTML.includes(big.name));assert(ctx.$('rides-list').innerHTML.includes(tower.name));
console.log('Passed: all 95 Disney age groups, sourced child tips separate from admission rules, no guessed ages, All Ages/unknown handling, actual list filtering and clear.');
