'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const preferences=require('../dist/preferences.js'),chart=require('../dist/chart-interaction.js'),surfaces=require('../dist/surfaces.js'),swipe=require('../dist/swipe-list.js'),waits=require('../dist/wait-times.js'),{updateNotice,candidates}=require('../server/push/decisions.cjs'),{allToday}=require('../dist/show-times.js');
assert.deepEqual(preferences.load({getItem:()=>null},'a'),{singleRiderAlerts:false,child:null});assert.equal(preferences.normalize({child:{age:7,height:125}}).child.height,125);assert.equal(preferences.normalize({child:{age:NaN,height:125}}).child,null);assert.equal(preferences.normalize(null)?.child,null);
const now=Date.parse('2026-10-06T10:07:00Z'),entry=m=>({status:'OPERATING',minutes:m,baselineMinutes:10,baselineSamples:4,updatedAt:new Date(now).toISOString()});
assert(waits.opportunity(entry(8),0,now));assert.equal(waits.opportunity(entry(9),0,now),null);assert.equal(waits.bestOpportunity(entry(9),entry(5),1,false,now),null);assert.equal(waits.bestOpportunity(entry(9),entry(5),1,true,now).lane,'Single Rider');assert.equal(waits.bestOpportunity(entry(9),{...entry(5),status:'CLOSED'},1,true,now),null);
assert.equal(updateNotice({appBuild:76},77,now).kind,'update');assert.equal(updateNotice({appBuild:77},77,now),null);assert.equal(updateNotice({appBuild:78},77,now),null);
assert.equal(chart.minute(now),727);assert.equal(chart.minute(Date.parse('2026-01-06T10:07:00Z')),667);assert.equal(chart.clock(727),'12:07');const series=[{label:'Normal',samples:[{from:600,to:615,minutes:0},{from:630,to:645,minutes:37.5}]},{label:'Single Rider',samples:[{from:600,to:630,minutes:5}]}];assert.equal(chart.probe(series,610)[0].value,0);assert.equal(chart.probe(series,615)[0].value,null);assert.equal(chart.probe(series,638)[0].value,37.5);
let caption={textContent:''},line={removeAttribute(){},setAttribute(k,v){this[k]=v;}},svg={dataset:{chartStart:'600',chartEnd:'660',chartView:'average',chartSeries:JSON.stringify(series)},getBoundingClientRect:()=>({left:0,width:336}),querySelector:()=>line,parentElement:{querySelector:()=>caption},isConnected:true},handlers={};const original=global.setInterval;global.setInterval=()=>{};chart.init({addEventListener:(k,f)=>handlers[k]=f});global.setInterval=original;handlers.pointerdown({target:{closest:()=>svg},pointerId:1,clientX:36+280/6});assert.match(caption.textContent,/10:10 Uhr · Normal: Ø 0 Min/);handlers.pointermove({pointerId:1,clientX:36+280/3});assert.match(caption.textContent,/10:20 Uhr · Normal: keine Messung/);handlers.pointerup({});
assert.equal(surfaces.kind('wait-history-dialog'),'page');assert.equal(surfaces.kind('queue-dialog'),'sheet');assert.equal(surfaces.sheetAction(false,{x:100,y:200,atTop:true},{x:100,y:120}),'expand');assert.equal(surfaces.sheetAction(true,{x:100,y:120,atTop:true},{x:100,y:210}),'collapse');assert.equal(surfaces.sheetAction(false,{x:100,y:120,atTop:true},{x:100,y:210}),'close');assert(surfaces.gesture('sheet',{x:20,y:100,atTop:true},{x:25,y:190}));assert(!surfaces.gesture('sheet',{x:20,y:100,atTop:false},{x:25,y:190}));assert(!surfaces.gesture('page',{x:100,y:100},{x:220,y:100}));assert(surfaces.gesture('page',{x:10,y:100},{x:120,y:105}));
assert(swipe.reveal(-80,10));assert(!swipe.reveal(-20,90));assert(!swipe.reveal(80,0));assert.equal(swipe.offset(-400,0,240),-240);assert.equal(swipe.offset(400,-240,240),0);assert.deepEqual(swipe.labels({favorite:true,hidden:true,visited:true}).map(x=>x.text),['Fav entfernen','Einblenden','Besucht entfernen']);
const data={rides:[{id:'ride-a',name:'A',category:'show',node:1,themeparksId:'a'},{id:'ride-a2',name:'Duplicate',category:'show',node:1,themeparksId:'a'},{id:'ride-b',name:'B',category:'show',node:2,themeparksId:'b'}]},router={snap:()=>({node:0,distance:0}),tree:()=>({ds:[0,200,100]})},shows=new Map([['a',{status:'OPERATING',showtimes:[{startTime:'2026-10-06T09:00:00+02:00'}]}],['b',{status:'CLOSED',showtimes:[{startTime:'2026-10-06T18:00:00+02:00'},{startTime:'2026-10-06T20:00:00+02:00'}]}]]);const all=allToday(data,shows,router,{latlng:[0,0]},now,now);assert.deepEqual(all.map(x=>x.ride.id),['ride-b','ride-a']);assert(all[0].closed);assert(all[1].finished);assert.equal(allToday(data,shows,router,null,now,now-300001).length,0);
const source=fs.readFileSync(__dirname+'/../dist/app.js','utf8'),ctx={planning:false,pointById:new Map([['ride-a',{}]]),uninterested:new Set(),favorites:new Set(),visited:new Set(['ride-a']),window:{confirm:()=>false},save(){throw Error('cancel must not save');},toggleFavorite(id){ctx.favorites.has(id)?ctx.favorites.delete(id):ctx.favorites.add(id);},setUninterested(id,on){on?ctx.uninterested.add(id):ctx.uninterested.delete(id);},renderHiddenTargets(){}};vm.createContext(require('./helpers/near-park.cjs')(ctx));vm.runInContext(source.slice(source.indexOf('async function applyListAction('),source.indexOf('function nearbyShowChoices(')),ctx);
(async()=>{await ctx.applyListAction('ride-a','favorite');assert(ctx.favorites.has('ride-a'));await ctx.applyListAction('ride-a','favorite');assert(!ctx.favorites.has('ride-a'));await ctx.applyListAction('ride-a','hidden');assert(ctx.uninterested.has('ride-a'));await ctx.applyListAction('ride-a','hidden');assert(!ctx.uninterested.has('ride-a'));await ctx.applyListAction('ride-a','visited');assert(ctx.visited.has('ride-a'));console.log('Passed: 20% threshold, optional Single Rider, child profiles, chart scrub including gaps/zero, swipe directions and reversible actions, show tabs, update builds.');})().catch(e=>{console.error(e);process.exitCode=1;});

const gpsctx={Date:{now:()=>now},position:null,lastFix:0,heading:null,headingAt:0,nav:false,gpsWantNav:false,RouteCore:{distance:()=>0},updateUser(){this.updated=true;},router:{snap:()=>({distance:100})},$:()=>({}),insidePark:()=>false};gpsctx.updateUser=()=>{gpsctx.updated=true;};vm.createContext(require('./helpers/near-park.cjs')(gpsctx));vm.runInContext(source.slice(source.indexOf('async function handleGPSPosition('),source.indexOf('function refreshGPSFix(')),gpsctx);const fix=(timestamp,latitude=48.86)=>({timestamp,coords:{latitude,longitude:2.78,accuracy:8}});gpsctx.handleGPSPosition(fix(now-25000));assert.equal(gpsctx.position,null);gpsctx.handleGPSPosition(fix(now-5000));assert.equal(gpsctx.lastFix,now-5000);assert.equal(gpsctx.position.latlng[0],48.86);gpsctx.handleGPSPosition(fix(now-10000,48.9));assert.equal(gpsctx.position.latlng[0],48.86);gpsctx.handleGPSPosition(fix(now+10000,48.9));assert.equal(gpsctx.position.latlng[0],48.86);console.log('Passed: stale, out-of-order and future GPS fixes do not overwrite the current position; real source timestamp is retained.');
