'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),models=require('../dist/park-models.js'),camera=require('../dist/map-3d.js');
const scene=JSON.parse(fs.readFileSync(__dirname+'/../dist/park-scene.json')),park=JSON.parse(fs.readFileSync(__dirname+'/../dist/park-data.json'));
assert(!scene.photoRoofs);assert.equal(models.photoLayer,undefined);assert(!fs.readFileSync(__dirname+'/../dist/sw.js','utf8').includes('park-ortho.jpg'));
assert(scene.roofMeshes.vertices.every(Number.isFinite));assert(scene.roofMeshes.shapes.gabled>100&&scene.roofMeshes.shapes.round>0);
const tower=scene.landmarks.find(l=>l.kind==='tower'),space=scene.landmarks.find(l=>l.kind==='space'),arendelle=scene.landmarks.find(l=>l.kind==='arendelle');
assert.equal(tower.sourceId,'way225080040');assert.equal(scene.features.features.find(f=>f.id===tower.sourceId).properties.height,12,'59m belongs to the hotel tower, not the whole footprint');
assert.equal(space.sourceId,'relation3958220');assert(space.width>70);assert(Math.abs(space.latlng[0]-48.87405)<.00001,'The dome uses its footprint centre, not the entrance');assert.equal(arendelle.name,'A Celebration in Arendelle');
for(const l of scene.landmarks){assert.deepEqual(camera.roofLocation(scene,{id:l.rideId,latlng:[0,0]}).lnglat,l.latlng.slice().reverse());}
for(const s of scene.facadeSigns){assert(s.center.every(Number.isFinite));assert(s.width>0&&s.height>0);assert(Math.abs(Math.hypot(...s.axis)-1)<1e-8);assert(Math.abs(s.axis[0]*s.normal[0]+s.axis[1]*s.normal[1])<1e-8);}
const sign=scene.facadeSigns.find(s=>s.rideId===tower.rideId);assert.deepEqual(sign.lines,['The','HOLLYWOOD','TOWER','Hotel']);assert.equal(sign.center[2],39);
const escaped=decodeURIComponent(models.mark({name:'A <B> & C'}));assert(escaped.includes('&lt;B&gt;')&&escaped.includes('&amp;'));
// Exercise actual facade atlas/vertical quads and restore shared MapLibre GL state.
const canvas={getContext:()=>({fillRect(){},strokeRect(){},fillText(){},strokeText(){}})};global.document={createElement:()=>canvas};
const state=new Map(),deleted=[],notes=[];let data,drawn;const gl={};
for(const [i,k] of ['VERTEX_ARRAY_BINDING','ARRAY_BUFFER_BINDING','ACTIVE_TEXTURE','UNPACK_FLIP_Y_WEBGL','TEXTURE_BINDING_2D','MAX_TEXTURE_SIZE','TEXTURE0','TEXTURE_2D','VERTEX_SHADER','FRAGMENT_SHADER','COMPILE_STATUS','LINK_STATUS','ARRAY_BUFFER','STATIC_DRAW','FLOAT','RGBA','UNSIGNED_BYTE','TEXTURE_MIN_FILTER','TEXTURE_MAG_FILTER','LINEAR','TEXTURE_WRAP_S','TEXTURE_WRAP_T','CLAMP_TO_EDGE','CURRENT_PROGRAM','CULL_FACE','TRIANGLES'].entries())gl[k]=i+1;
state.set(gl.VERTEX_ARRAY_BINDING,'old-vao');state.set(gl.ARRAY_BUFFER_BINDING,'old-buffer');state.set(gl.ACTIVE_TEXTURE,123);state.set(gl.UNPACK_FLIP_Y_WEBGL,true);state.set(gl.TEXTURE_BINDING_2D,'old-texture');state.set(gl.CURRENT_PROGRAM,'old-program');state.set(gl.MAX_TEXTURE_SIZE,4096);
Object.assign(gl,{getParameter:k=>state.get(k),activeTexture:v=>state.set(gl.ACTIVE_TEXTURE,v),bindTexture:(t,v)=>state.set(gl.TEXTURE_BINDING_2D,v),pixelStorei:(k,v)=>state.set(k,v),bindVertexArray:v=>state.set(gl.VERTEX_ARRAY_BINDING,v),bindBuffer:(t,v)=>state.set(gl.ARRAY_BUFFER_BINDING,v),useProgram:v=>state.set(gl.CURRENT_PROGRAM,v),createShader:()=>({}),shaderSource(){},compileShader(){},getShaderParameter:()=>true,createProgram:()=>({}),attachShader(){},linkProgram(){},getProgramParameter:()=>true,createVertexArray:()=>({}),createBuffer:()=>({}),bufferData:(t,v)=>data=v,getAttribLocation:()=>0,enableVertexAttribArray(){},vertexAttribPointer(){},getUniformLocation:()=>0,createTexture:()=>({}),texImage2D(){},texParameteri(){},uniform1i(){},uniformMatrix4fv(){},drawArrays:(t,f,n)=>drawn=n,isEnabled:()=>true,disable(){},enable(){}});
for(const name of ['Shader','Texture','Buffer','VertexArray','Program'])gl['delete'+name]=v=>deleted.push(name);
const layer=models.signLayer({MercatorCoordinate:{fromLngLat:()=>({x:.5,y:.3,z:0,meterInMercatorCoordinateUnits:()=>1})}},scene,e=>notes.push(e));layer.onAdd({},gl);assert(!layer.disabled);assert.equal(notes.at(-1).name,'signs-ready');assert.equal(data.length,scene.facadeSigns.reduce((n,s)=>n+(s.vertices?.length||30),0));assert(data.every(Number.isFinite));
let offset=0;for(const s of scene.facadeSigns){if(!s.vertices){assert.equal(data[offset+2],data[offset+7]);assert.equal(data[offset+12],data[offset+22]);assert(data[offset+12]>data[offset+2],'Rectangular world sign is vertical');}else{assert(s.vertices.length%15===0);for(let i=0;i<s.vertices.length;i+=5){assert(s.vertices[i+3]>=0&&s.vertices[i+3]<=1);assert(s.vertices[i+4]>=0&&s.vertices[i+4]<=1);}}offset+=s.vertices?.length||30;}
assert.equal(state.get(gl.VERTEX_ARRAY_BINDING),'old-vao');assert.equal(state.get(gl.ACTIVE_TEXTURE),123);assert.equal(state.get(gl.TEXTURE_BINDING_2D),'old-texture');assert.equal(state.get(gl.UNPACK_FLIP_Y_WEBGL),true);
layer.render(gl,{defaultProjectionData:{mainMatrix:[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}});assert.equal(drawn,scene.facadeSigns.reduce((n,s)=>n+(s.vertices?.length/5||6),0));assert.equal(state.get(gl.CURRENT_PROGRAM),'old-program');assert.equal(state.get(gl.ACTIVE_TEXTURE),123);assert.equal(state.get(gl.TEXTURE_BINDING_2D),'old-texture');layer.onRemove({},gl);for(const k of ['Texture','Buffer','VertexArray','Program'])assert(deleted.includes(k));
const roof=models.roofLayer({MercatorCoordinate:{fromLngLat:()=>({x:.5,y:.3,z:0,meterInMercatorCoordinateUnits:()=>1})}},scene,e=>notes.push(e));roof.onAdd({},gl);assert(!roof.disabled);assert.equal(notes.at(-1).name,'roof-lettering-ready');assert.equal(data.length,scene.roofLettering.labels.reduce((n,l)=>n+l.vertices.length,0));assert(data.every(Number.isFinite));roof.render(gl,{defaultProjectionData:{mainMatrix:[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}});roof.onRemove({},gl);assert.equal(state.get(gl.ACTIVE_TEXTURE),123);assert.equal(state.get(gl.TEXTURE_BINDING_2D),'old-texture');
assert(scene.roofLettering.labels.length+scene.roofFlags.length>=120);for(const label of scene.roofLettering.labels){assert(label.name&&label.sourceId);assert(label.vertices.length%15===0);for(let i=0;i<label.vertices.length;i+=5){assert(label.vertices[i+2]>0);assert(label.vertices[i+3]>=-.00001&&label.vertices[i+3]<=1.00001);assert(label.vertices[i+4]>=-.00001&&label.vertices[i+4]<=1.00001);}}const cameraSource=fs.readFileSync(__dirname+'/../dist/map-3d.js','utf8');assert(!cameraSource.includes('map-3d-roof-brand')&&!cameraSource.includes('roofMarkers'),'Roof names are painted meshes, never HTML billboards');
state.set(gl.MAX_TEXTURE_SIZE,512);const failed=models.signLayer({},scene,e=>notes.push(e));failed.onAdd({},gl);assert(failed.disabled);assert.equal(notes.at(-1).name,'signs-error');assert.equal(state.get(gl.ACTIVE_TEXTURE),123);delete global.document;
console.log('Passed: geometric roofs, source landmark anchors, tower relief, real vertical facade signs, SVG escaping, shared GL state, bounded atlas, optional failure and GPU cleanup.');
