'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const dist=process.argv[2]||__dirname+'/../dist';
function harness(){const nodes=new Map(),timers=new Map(),intervals=new Map(),events=new Map();let serial=0;const doc={querySelectorAll:()=>[],getElementById:id=>{if(!nodes.has(id))nodes.set(id,{hidden:false,value:0,attrs:{},setAttribute(k,v){this.attrs[k]=v;},removeAttribute(k){delete this.attrs[k];},addEventListener(k,v){this[k]=v;}});return nodes.get(id);}};
 const ctx={document:doc,URL,Date,TextDecoder,AbortController,setTimeout:(fn,ms)=>{timers.set(++serial,{fn,ms});return serial;},clearTimeout:id=>timers.delete(id),setInterval:(fn,ms)=>{intervals.set(++serial,{fn,ms});return serial;},clearInterval:id=>intervals.delete(id),location:{href:'https://example.test/App/',replace(url){this.replaced=url;}},addEventListener:(k,fn)=>events.set(k,fn)};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(dist+'/startup.js','utf8'),ctx);return{ctx,nodes,timers,intervals,events};}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
 let h=harness(),reads=[],signal;
 h.ctx.fetch=async(url,options)=>{signal=options.signal;return{ok:true,body:{getReader:()=>({read(){return new Promise((resolve,reject)=>{reads.push(resolve);signal.addEventListener('abort',()=>reject(Error('aborted')),{once:true});});},releaseLock(){}})}};};
 const bytes=new TextEncoder().encode('{"name":"Mickey 🐭"}');let promise=h.ctx.DisneyStartup.loadJSON('park-data.json',bytes.length);await tick();
 assert.equal(h.nodes.get('startup-progress').value,0);assert.match(h.nodes.get('startup-status').textContent,/Donald/);
 h.intervals.values().next().value.fn();assert.match(h.nodes.get('startup-status').textContent,/Mickey/);
 const oldIdle=[...h.timers.keys()].find(id=>h.timers.get(id).ms===45000);
 reads.shift()({done:false,value:bytes.slice(0,17)});await tick();assert(h.nodes.get('startup-progress').value>0&&h.nodes.get('startup-progress').value<100);assert(!h.timers.has(oldIdle),'Each real chunk renews the inactivity deadline');assert.equal(signal.aborted,false);
 reads.shift()({done:false,value:bytes.slice(17)});await tick();assert.equal(h.nodes.get('startup-progress').value,99,'Never claim completion before EOF and valid JSON');
 reads.shift()({done:true});assert.equal((await promise).name,'Mickey 🐭','UTF-8 character split between chunks is preserved');assert.equal(h.nodes.get('startup-progress').value,100);assert.equal(h.intervals.size,0);assert(![...h.timers.values()].some(t=>t.ms===45000));h.ctx.DisneyStartup.status('Parkkarte wird geladen …');h.ctx.DisneyStartup.finish();assert.equal(h.nodes.get('startup-screen').hidden,true);assert.equal(h.timers.size,0);
 h=harness();h.ctx.fetch=(url,{signal})=>new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(Error('abort'))));promise=h.ctx.DisneyStartup.loadJSON('park',20);const rejected=assert.rejects(promise,{name:'StartupDownloadError'});[...h.timers.values()].find(t=>t.ms===45000).fn();await rejected;h.ctx.DisneyStartup.fail({name:'StartupDownloadError',message:'Der Download ist ins Stocken geraten. Bitte erneut versuchen.'});assert.equal(h.nodes.get('startup-retry').hidden,false);assert.equal(h.intervals.size,0);assert.equal(h.timers.size,0);
 h=harness();h.ctx.fetch=async()=>({ok:true,json:async()=>({fallback:true})});assert.equal((await h.ctx.DisneyStartup.loadJSON('park',20)).fallback,true);assert.equal(h.nodes.get('startup-progress').value,100);
 h=harness();h.ctx.fetch=async()=>({ok:true,body:{getReader:()=>{let count=0;return{read:async()=>++count===1?{done:false,value:new TextEncoder().encode('{bad')}:{done:true},releaseLock(){}};}}});await assert.rejects(h.ctx.DisneyStartup.loadJSON('park',4));assert.equal(h.nodes.get('startup-progress').value,99,'Invalid JSON never completes');assert.equal(h.intervals.size,0);
 h=harness();let midSignal,pendingRead;h.ctx.fetch=async(url,{signal})=>{midSignal=signal;let count=0;return{ok:true,body:{getReader:()=>({read:()=>++count===1?Promise.resolve({done:false,value:new TextEncoder().encode('{')}):new Promise((resolve,reject)=>{pendingRead=true;signal.addEventListener('abort',()=>reject(Error('abort')));}),releaseLock(){}})}};};promise=h.ctx.DisneyStartup.loadJSON('park',10);await tick();assert(pendingRead);assert.equal(h.nodes.get('startup-progress').value,10);const midRejected=assert.rejects(promise,{name:'StartupDownloadError'});[...h.timers.values()].find(t=>t.ms===45000).fn();await midRejected;assert(midSignal.aborted);assert.equal(h.nodes.get('startup-progress').value,10);assert.equal(h.intervals.size,0);
 h=harness();h.ctx.fetch=async()=>({ok:false});await assert.rejects(h.ctx.DisneyStartup.loadJSON('park',20),/Kartendaten/);assert.equal(h.nodes.get('startup-progress').value,0);assert.equal(h.intervals.size,0);
 h=harness();h.events.get('error')({target:{tagName:'SCRIPT',src:'https://example.test/app.js?v=112'}});h.ctx.DisneyStartup.finish();assert.notEqual(h.nodes.get('startup-screen').hidden,true);
 const html=fs.readFileSync(dist+'/index.html','utf8'),app=fs.readFileSync(dist+'/app.js','utf8');assert(html.includes('<progress id="startup-progress"'));assert(app.includes("loadJSON('park-data.json?v=42',8494350)"));assert(!app.includes("fetch('park-data.json?v=42',{cache:'no-store',signal:AbortSignal.timeout(15000)})"));
 console.log('Passed: streamed real percentages, UTF-8 boundaries, rotating messages, slow-download heartbeat, stalled-download abort, fallback, failure, completion.');
})().catch(e=>{console.error(e);process.exitCode=1;});
