const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{Router}=require('../dist/routing.js');
const data=JSON.parse(fs.readFileSync(__dirname+'/../dist/park-data.json')),router=new Router(data),source=fs.readFileSync(__dirname+'/../dist/app.js','utf8');
assert.equal(data.services.filter(p=>p.serviceType==='water').length,26);assert.equal(data.services.filter(p=>p.serviceType==='restaurant').length,46);
const ids=new Set(),start=data.rides[0].node;
for(const p of data.services){assert(!ids.has(p.id));ids.add(p.id);assert.deepEqual(p.latlng,data.nodes[p.node]);assert.equal(p.offset,0);assert(p.approachMeters<=90);assert.equal(router.leg(start,p.node).path.at(-1).join(','),p.latlng.join(','));assert(Number.isFinite(router.leg(p.node,start).distance));assert(['Disneyland Park','Disney Adventure World'].includes(p.park));}
assert(!data.services.some(p=>/Five Guys|Vapiano|Rainforest|Cape Cod/.test(p.name)),'Village and hotel amenities must not be silently assigned to either park');
assert(data.services.some(p=>p.name==='PYM Kitchen'));assert(data.services.some(p=>p.name==='Nordic Crowns Tavern'));
const nodes=new Map(),$=id=>{if(!nodes.has(id))nodes.set(id,{dataset:{},value:'',setAttribute(){},addEventListener(){},close(){},showModal(){this.open=true;}});return nodes.get(id);};
let origin=data.nodes[data.rides[0].node],ended=null;
const ctx={DisneyRestaurantSearch:require('../dist/restaurant-search.js'),$,data,router,origin,originLabel:'Parkeingang',selectedPark:'all',planning:false,parkMatches:p=>ctx.selectedPark==='all'||p.park===ctx.selectedPark,pointById:new Map([...data.rides,...data.services].map(p=>[p.id,p])),remaining:()=>[data.rides[0]],route:{order:[data.rides[0].id]},finishQueueForNavigation:id=>ended=id,playerDismissed:true,pinnedWC:null,priorityRide:null,save(){},homeView(){},showNavigationMap(){ctx.usedSelectedMap=true;},replan:async()=>{ctx.route={order:[ctx.pinnedWC.id,ctx.priorityRide.id]};},toast(){},closeQueueForBrowse(){},esc:String,minutes:d=>Math.ceil(d/72),metric:Math.round};
vm.createContext(require('./helpers/near-park.cjs')(ctx));vm.runInContext(source.slice(source.indexOf('function facilityEntries('),source.indexOf('function loadPreferences(')),ctx);
(async()=>{const water=ctx.facilityEntries('water');assert(water.length===26);for(let i=1;i<water.length;i++)assert(water[i].meters>=water[i-1].meters);ctx.selectedPark='Disney Adventure World';assert(ctx.facilityEntries('restaurant').every(x=>x.point.park===ctx.selectedPark));assert.equal(ctx.facilityEntries('restaurant','pym')[0].point.name,'PYM Kitchen');const point=water.find(x=>x.point.park===ctx.selectedPark).point;assert(await ctx.navigateFacility(point.id));assert.equal(ended,point.id);assert.equal(ctx.pinnedWC,point);assert.equal(ctx.priorityRide,data.rides[0]);assert(ctx.usedSelectedMap);assert.equal(ctx.route.order[0],point.id);assert(!ctx.playerDismissed);
const html=fs.readFileSync(__dirname+'/../dist/index.html','utf8');const actions=html.slice(html.indexOf('<div class="nav-actions">'),html.indexOf('<div id="nav-details"'));assert(!actions.includes('id="nav-wc"'));assert(html.slice(html.indexOf('<div id="nav-details"')).includes('id="nav-wc"'));
console.log('Passed: 72 genuine mapped in-park amenities, no Village/hotel duplicates, public graph endpoints and return paths, distance/name/park filters, pause navigation preserves next ride and map mode, WC only under More.');})().catch(e=>{console.error(e);process.exitCode=1;});
