'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),I=require('../dist/i18n.js'),{candidates,updateNotice}=require('../server/push/decisions.cjs'),waitLib=require('../dist/wait-times.js'),data=JSON.parse(fs.readFileSync(__dirname+'/../dist/park-data.json'));
const now=Date.parse('2026-10-05T10:00:00Z'),show=data.rides.find(x=>x.name==='TOGETHER: a Pixar Musical Adventure'),queue=data.rides.find(x=>x.name==='Big Thunder Mountain');
const state={appBuild:93,context:{at:now/1000,candidates:[{id:show.id,meters:200},{id:queue.id,meters:300,extraWalkingMinutes:2,favorite:true}]}},shows=new Map([[show.themeparksId,{status:'OPERATING',showtimes:[{startTime:'2026-10-05T12:20:00+02:00'}]}]]),waits=new Map([[`${queue.queueTimes.parkId}:${queue.queueTimes.rideId}`,{status:'OPERATING',minutes:10,baselineMinutes:40,baselineSamples:12,updatedAt:new Date(now).toISOString()}]]);
const de=candidates(state,data,waits,shows,now,waitLib);assert.equal(de.length,2);
for(const [lang] of I.languages){state.language=lang;const notices=candidates(state,data,waits,shows,now,waitLib);assert.deepEqual(notices.map(n=>[n.id,n.key,n.kind,n.expires]),de.map(n=>[n.id,n.key,n.kind,n.expires]),'language cannot alter relevance, admission or timing');assert(notices[0].body.includes(I.name(show,lang)));if(lang!=='de'){for(const n of notices){assert(!/beginnt bald|Ungewöhnlich|Fußweg|vorher da sein|möchtest|statt meist/.test(n.title+' '+n.body),n.body);}assert(!/Öffne|verfügbar|ist bereit/.test(updateNotice(state,94,now).body));}}
assert.equal(updateNotice({...state,appBuild:94},94,now),null);state.language='invalid';assert.equal(candidates(state,data,waits,shows,now,waitLib)[0].title,de[0].title);
// Only the locale code enters the worker cache. Authenticated navigations are never cached.
const handlers={},stored=new Map(),scope='https://weletapi.com/files/.internal/Disney/';let task,notification;
const ctx={URL,Response,DisneyI18n:I,self:{location:{origin:'https://weletapi.com'},registration:{scope,showNotification:async(title,opts)=>notification={title,...opts}},addEventListener:(type,fn)=>handlers[type]=fn},caches:{open:async()=>({put:async(k,v)=>stored.set(k,v),match:async k=>stored.get(k)?.clone()})},fetch:async()=>{throw Error('offline');}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/../dist/sw.js','utf8'),ctx);
(async()=>{handlers.message({data:{type:'disney-language',language:'ar',gps:[48,2],child:{age:7}},waitUntil:p=>task=p});await task;assert.deepEqual([...stored.keys()],['disney-language-preference']);assert.equal(await stored.get('disney-language-preference').clone().text(),'ar');let response;handlers.fetch({request:{url:scope,method:'GET',mode:'navigate'},respondWith:p=>response=p});const offline=await response;assert.equal(offline.status,503);const markup=await offline.text();assert(markup.includes('lang="ar" dir="rtl"'));assert(!markup.includes('Du bist offline'));assert(markup.includes('weletapi'));assert(!markup.includes('onclick='),'offline retry works without violating CSP');handlers.push({data:{json:()=>({kind:'test'})},waitUntil:p=>task=p});await task;assert.equal(notification.title,I.text('Disney · Neuer Hinweis','ar'));assert.equal(notification.body,I.text('In Disney gibt es einen neuen Hinweis.','ar'));
const php=fs.readFileSync(__dirname+'/../dist/push-api.php','utf8');assert(php.includes("$state['language']=disney_push_language"));assert(!php.includes("$state['gps']"));assert(!php.includes("$state['child']"));assert(fs.readFileSync(__dirname+'/../dist/push-client.js','utf8').includes("language:typeof DisneyI18n"));console.log('Passed: localized server show/wait/update pushes retain admission, relevance and deduplication; locale-only worker persistence, Arabic offline authentication notice, CSP-safe retry, default push and API wiring.');})().catch(e=>{console.error(e);process.exitCode=1;});
