'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),data=require('../dist/park-data.json'),audit=require('../sources/location-audit.json'),{Router,distance}=require('../dist/routing.js'),router=new Router(data);
assert.equal(audit.destinations.length,95);assert.equal(new Set(audit.destinations.map(r=>r.rideId)).size,95);
for(const entry of audit.destinations){const r=data.rides.find(r=>r.id===entry.rideId);assert(r);assert.deepEqual(r.latlng,data.nodes[r.node]);assert.deepEqual(r.latlng,entry.after);assert(entry.disneyMap.startsWith('https://'));assert.equal(r.locationReview.date,entry.reviewedAt||'2026-10-06');assert(Number.isFinite(router.tree(data.rides[0].node).ds[r.node]));if(r.category==='show'||r.category==='character')assert(['indoor','outdoor'].includes(r.eventSetting),r.name+' has a sourced event setting');if(entry.status==='variable-or-unspecified-area')assert(r.approximateArea,'Variable points are not presented as exact entrances');}
const arendelle=data.rides.find(r=>r.name==='A Celebration in Arendelle');assert(distance(arendelle.latlng,[48.8645505,2.7733521])<25);assert(audit.destinations.find(r=>r.rideId===arendelle.id).movedMeters>700);assert.equal(arendelle.eventSetting,'outdoor');
const together=data.rides.find(r=>r.name==='TOGETHER: a Pixar Musical Adventure');assert.deepEqual(together.latlng,[48.8670533,2.7798125]);assert.equal(together.eventSetting,'indoor');assert.equal(together.arrivalLeadMinutes,15);
const minnie=data.rides.find(r=>r.name==='Minnie’s Dream Factory');assert(distance(minnie.latlng,[48.8666175,2.7802029])<10);assert(distance(together.latlng,minnie.latlng)>50);
for(const r of data.rides.filter(r=>r.name.startsWith('Disneyland Railroad '))){const e=audit.destinations.find(e=>e.rideId===r.id);assert.deepEqual(e.before,e.after,'Station cannot be matched through an empty alias');}
assert(fs.statSync(__dirname+'/../dist/ride-summary.json').size<20000);const summary=require('../dist/ride-summary.json');assert.deepEqual(summary.rides.map(r=>r.id),data.rides.map(r=>r.id));assert(fs.readFileSync(__dirname+'/../dist/push-api.php','utf8').includes("__DIR__.'/ride-summary.json'"));
console.log('Passed: all 95 audited stable targets and reachable endpoints, official map provenance, no invented character pin precision, Arendelle waterfront, separate correct theaters, indoor/outdoor completeness and small push catalogue.');
