'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),camera=require('../dist/map-3d.js'),models=require('../dist/park-models.js');
const mobile={devicePixelRatio:3,matchMedia:()=>({matches:true})};assert.deepEqual(camera.renderBudget(false,mobile),{pixelRatio:1.5,trees:600,roofs:false});assert.equal(camera.renderBudget(true,mobile).pixelRatio,1);assert.equal(camera.renderBudget(false,{devicePixelRatio:1}).pixelRatio,1);
const scene=JSON.parse(fs.readFileSync(__dirname+'/../dist/park-scene.json')),park=JSON.parse(fs.readFileSync(__dirname+'/../dist/park-data.json'));const light=camera.modelScene(scene,600);assert.equal(light.features,scene.features,'All actual buildings, paths and water are unchanged');assert(light.trees.length<=600);assert(models.build(light,park.rides).length<models.build(scene,park.rides).length/2);
function element(){return {children:[],style:{},attrs:{},classList:{toggle(){}},append(...xs){this.children.push(...xs);},addEventListener(){},setAttribute(k,v){this.attrs[k]=v;},querySelector(k){if(k==='.cone')return {hidden:false};return this.children.find(x=>'.'+x.className===k);}};}
const node=element(),instances=[],timers=new Map(),events=[],canonicalEvents=new Map();let tid=0,fetches=0,throwConstructor=false,deferLoad=false;
const setTimer=(fn,ms)=>{timers.set(++tid,{fn,ms});return tid;},clearTimer=id=>timers.delete(id);
class MapMock{
 constructor(opts){if(throwConstructor){throwConstructor=false;throw Error('GPU unavailable');}this.opts=opts;this.handlers=new Map();this.data=new Map();instances.push(this);queueMicrotask(()=>{if(!deferLoad)this.fire('load');});}
 on(k,fn){if(!this.handlers.has(k))this.handlers.set(k,new Set());this.handlers.get(k).add(fn);return this;}off(k,fn){this.handlers.get(k)?.delete(fn);return this;}fire(k,e={}){for(const fn of [...this.handlers.get(k)||[]])fn(e);}
 getZoom(){return this.opts.zoom;}getPitch(){return this.opts.pitch;}getBearing(){return this.opts.bearing;}getCenter(){return {lng:this.opts.center[0],lat:this.opts.center[1]};}resize(){}jumpTo(o){Object.assign(this.opts,o);}remove(){this.removed=true;}
 getSource(id){return {setData:value=>this.data.set(id,value)};}addLayer(layer){this.layer=layer;}getLayer(){return this.layer;}removeLayer(){this.layer=null;}project(){return {x:0,y:0};}
}
class MarkerMock{constructor(o){this.el=o.element;}setLngLat(p){this.ll=p;return this;}addTo(){assert(this.ll,'A marker must receive its coordinates before attaching to the map');return this;}setRotation(){return this;}getElement(){return this.el;}getLngLat(){return this.ll;}remove(){}}
const canonical={getCenter:()=>({lng:2.78,lat:48.87}),getZoom:()=>18,getBearing:()=>27,setZoom(){},setView(){},setBearing(){},on:(k,fn)=>canonicalEvents.set(k,fn)};
const state={points:[{id:'ride-a',latlng:[48.87,2.78],html:'1',name:'Ride'}],rides:park.rides,path:[[48.87,2.78],[48.871,2.781]],position:{latlng:[48.87,2.78],accuracy:12},heading:20,waiting:false};
const ctx={console:{error(){},warn(){}},AbortController,ResizeObserver:class{observe(){}disconnect(){this.disconnected=true;}},fetch:async()=>{fetches++;return {ok:true,json:async()=>scene};},setTimeout:setTimer,clearTimeout:clearTimer,document:{getElementById:()=>node,createElement:element},DisneyModels:{layer:(lib,s)=>({id:'park-landmarks',treeCount:s.trees.length})},devicePixelRatio:3,matchMedia:mobile.matchMedia};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/../dist/map-3d.js','utf8'),ctx);
const diagnostics=[];const renderer=ctx.Disney3D.create(canonical,{loadLibrary:async()=>({Map:MapMock,Marker:MarkerMock,setWorkerCount(){}}),state:()=>state,onDiagnostic:e=>diagnostics.push(e),onReady:()=>events.push('ready'),onRecovering:()=>events.push('recovering'),onError:e=>events.push(e.code||'error'),onBearing(){}});
const drain=async()=>{for(let i=0;i<14;i++)await Promise.resolve();};
const recover=async()=>{const t=[...timers].find(([,v])=>v.ms===500);assert(t);timers.delete(t[0]);t[1].fn();await drain();};
(async()=>{
 await Promise.all([renderer.open(),renderer.open()]);assert.equal(instances.length,1,'Rapid navigation does not allocate extra contexts');assert.equal(instances[0].opts.pixelRatio,1.5);assert(!instances[0].opts.style.layers.some(x=>x.id==='roofs'));assert.equal(instances[0].data.get('navigation').features.length,1);assert.equal(instances[0].layer.treeCount,600);
 assert.equal(instances[0].opts.minZoom,0);const style=instances[0].opts.style;assert(style.projection.type.includes('vertical-perspective'));assert.equal(style.layers.find(l=>l.id==='world-land').paint['fill-color'],'#8fbc79');assert.equal(style.layers.find(l=>l.id==='background').paint['background-color'],'#4ba8d1');assert.equal(style.layers.find(l=>l.id==='paris-outline').minzoom,7);assert(style.layers.filter(l=>l.source==='park').every(l=>l.minzoom===14));assert.equal(style.sources.world.maxzoom,8);
 assert(diagnostics.some(e=>e.name==='map-load'));assert(diagnostics.some(e=>e.name==='ready'));const first=instances[0];first.fire('render');first.fire('sourcedata',{sourceId:'park',isSourceLoaded:true});assert(diagnostics.some(e=>e.name==='first-frame'));assert(diagnostics.some(e=>e.name==='source-ready'&&e.source==='park'));assert(!JSON.stringify(diagnostics).includes('latlng')); first.opts.pitch=42;first.fire('webglcontextlost');assert(first.removed);assert(renderer.isActive());assert.equal(events.at(-1),'recovering');assert(!events.includes('context-lost'));await recover();assert.equal(instances.length,2);assert.equal(instances[1].opts.pixelRatio,1);assert.equal(instances[1].opts.pitch,42);assert.equal(instances[1].opts.bearing,-27);assert.equal(instances[1].layer.treeCount,180);assert.equal(fetches,1,'Recovery reuses downloaded geometry');assert.equal(instances[1].data.get('navigation').features.length,1,'Route rebuilt after source caches cleared');
 first.fire('webglcontextlost');assert.equal(instances.length,2,'Removed renderer cannot disturb the new one');
 instances[1].fire('webglcontextlost');await recover();assert.equal(instances.length,3);instances[2].fire('webglcontextlost');assert.equal(events.at(-1),'context-lost');assert(![...timers.values()].some(x=>x.ms===500),'Recovery is bounded');
 throwConstructor=true;await renderer.open();assert.equal(events.at(-1),'error','Synchronous constructor failure is handled without promise self-reference errors');await renderer.open();assert.equal(events.at(-1),'ready','Manual retry remains usable');
 instances.at(-1).fire('webglcontextlost');renderer.close();assert.equal(node.hidden,true);assert(![...timers.values()].some(x=>x.ms===500),'Explicit 2D choice cancels pending recovery');
 const before=instances.length;await renderer.open();assert.equal(instances.length,before+1);assert.equal(events.at(-1),'ready');assert.equal(timers.size,0,'No leaked load timers');
 state.position={latlng:[48.87,2.78],accuracy:12};state.heading=20;renderer.sync();assert.equal(events.at(-1),'ready','Live GPS must not turn a loaded 3D map into a loading failure');
 instances.at(-1).fire('webglcontextlost');renderer.close();deferLoad=true;const opening=renderer.open();await drain();instances.at(-1).fire('render');const timeout=[...timers].find(([,v])=>v.ms===15000);assert(timeout);timeout[1].fn();await opening;const failure=diagnostics.findLast(e=>e.name==='failed');assert.equal(failure.code,'timeout');assert.equal(failure.frames,1,'Already rendered scene followed by incomplete load is distinguishable');assert.equal(failure.loaded,false);assert(diagnostics.some(e=>e.name==='context-lost'&&e.loaded===true));
 console.log('Passed: bounded context recovery, GPU budgets, optional trees, route/targets/camera preserved, no repeated scene fetch or contexts, late old events, constructor failures, manual retry and explicit 2D cancellation.');
})().catch(e=>{console.error(e);process.exitCode=1;});
