'use strict';
const assert=require('node:assert/strict'),D=require('../dist/map-diagnostics.js');
function fixture(){const storage=new Map(),timers=new Map(),listeners=new Map(),calls=[],status=[];let tid=0,fail=false;const env={navigator:{userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 Version/18.6 Mobile Safari/604.1',onLine:true,standalone:true},innerWidth:390,innerHeight:844,devicePixelRatio:3,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},setTimeout:(fn,ms)=>{timers.set(++tid,{fn,ms});return tid;},clearTimeout:id=>timers.delete(id),addEventListener:(k,fn)=>listeners.set(k,fn),fetch:async(url,o={})=>{calls.push({url,...o});if(fail)throw Error('offline');return {ok:true,status:200,json:async()=>o.method==='POST'?{ok:true,id:'012345abcdef'}:{csrf:'a'.repeat(64)}};}};return {env,storage,timers,listeners,calls,status,setFail:x=>fail=x,options:{build:84,getModel:()=> 'iPhone 15 Pro',onStatus:(...s)=>status.push(s)}};}
(async()=>{
 const f=fixture(),d=D.create(f.options,f.env);assert.deepEqual(D.environment(f.env),{browser:'Safari',version:'18.6',platform:'iOS',osVersion:'18.6',pixelRatio:3,width:390,height:844,standalone:true});
 const secret='https://weletapi.com/foo?gps=48.870500,2.779720&token='+ 'f'.repeat(64),error={name:'failed',code:'timeout',message:`Bad ${secret} me@example.com at 48.870500,2.779720 and 48.87,2.78`,latlng:[48.87,2.78],route:[['private']],user:'test-account',stack:'private stack'};
 d.record({name:'open'});d.record({name:'first-frame',frames:1,sourceLoaded:false});d.record(error);assert.equal(f.calls.length,0,'Error collection is buffered');assert(await d.flush());const post=f.calls.find(x=>x.method==='POST'),p=JSON.parse(post.body),encoded=post.body;assert.equal(p.environment.model,'iPhone 15 Pro');assert.equal(p.environment.modelSource,'manual');assert.equal(p.reason,'failed');assert(p.events.some(e=>e.name==='first-frame'));for(const text of ['48.87','2.78','private','test-account','me@example.com','gps=','token=','latlng','route'])assert(!encoded.includes(text),text);assert.equal(post.headers['X-Disney-CSRF'],'a'.repeat(64));assert.equal(post.keepalive,true);assert.equal(f.status.at(-1)[0],'sent');assert.equal(f.storage.has('disney:3d-diagnostic-pending'),false);
 f.env.navigator.onLine=false;d.record({name:'context-lost'});assert.equal(await d.flush(),false);assert(f.storage.has('disney:3d-diagnostic-pending'));f.env.navigator.onLine=true;f.setFail(true);assert.equal(await d.flush(),false);assert.equal(f.status.at(-1)[0],'pending');f.setFail(false);assert(await d.flush());
 for(let i=0;i<80;i++)d.record({name:'loading-move',moves:i,latitude:48.87});await d.send();assert.equal(JSON.parse(f.calls.at(-1).body).events.length,32);
 const g=fixture();g.storage.set('disney:3d-diagnostic-checkpoint',f.storage.get('disney:3d-diagnostic-checkpoint'));const resumed=D.create(g.options,g.env);await resumed.flush();assert.equal(JSON.parse(g.calls.at(-1).body).reason,'previous-interrupted');g.listeners.get('pagehide')();assert(!g.storage.has('disney:3d-diagnostic-checkpoint'));
 const android=fixture();android.env.navigator.userAgent='Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro Build/ABC) Chrome/132.0';android.options.getModel=()=>'';const a=D.create(android.options,android.env);await a.send();assert.equal(JSON.parse(android.calls.at(-1).body).environment.model,'Pixel 9 Pro');
 // Ask only after a crash; retain existing manually saved models from older builds.
 const fresh=fixture();fresh.options.getModel=()=>'';let asks=0;
 fresh.options.onModelNeeded=async()=>{asks++;return 'iPhone 16 Pro';};
 const prompted=D.create(fresh.options,fresh.env);prompted.record({name:'open'});prompted.record({name:'ready'});await Promise.resolve();assert.equal(asks,0,'No model question on healthy startup');
 await prompted.send();assert.equal(asks,0,'Manual diagnostic button does not ask for a model');
 prompted.record({name:'context-lost'});assert(await prompted.flush());assert.equal(asks,1);assert.equal(fresh.storage.get('disney:diagnostic-model'),'iPhone 16 Pro');assert.equal(JSON.parse(fresh.calls.at(-1).body).environment.model,'iPhone 16 Pro','Include the answer in this crash report');
 prompted.record({name:'failed'});await prompted.flush();assert.equal(asks,1,'Several errors in one crash do not repeat the question');
 const reopened=D.create(fresh.options,fresh.env);reopened.record({name:'failed'});await reopened.flush();assert.equal(asks,1,'Next app launch reuses the local answer');assert.equal(JSON.parse(fresh.calls.at(-1).body).environment.model,'iPhone 16 Pro');
 const skipped=fixture();skipped.options.getModel=()=>'';let skips=0;skipped.options.onModelNeeded=async()=>{skips++;return '';};const optional=D.create(skipped.options,skipped.env);optional.record({name:'failed'});assert(await optional.flush());assert.equal(skips,1);assert(!skipped.storage.has('disney:diagnostic-model'));assert(!('model' in JSON.parse(skipped.calls.at(-1).body).environment),'Skipping still sends the technical report without a model');optional.record({name:'context-lost'});await optional.flush();assert.equal(skips,1,'Skipping does not nag again during this session');
 const offline=fixture();offline.options.getModel=()=>'';let offlineAsks=0;offline.options.onModelNeeded=async()=>{offlineAsks++;return 'iPhone 15';};offline.env.navigator.onLine=false;const buffered=D.create(offline.options,offline.env);buffered.record({name:'failed'});await Promise.resolve();await Promise.resolve();await Promise.resolve();assert.equal(offlineAsks,1,'Ask after the crash even while offline');assert.equal(await buffered.flush(),false);offline.env.navigator.onLine=true;await buffered.flush();assert.equal(JSON.parse(offline.calls.at(-1).body).environment.model,'iPhone 15');
 const interrupted=fixture();interrupted.options.getModel=()=>'';let resumedAsks=0;interrupted.options.onModelNeeded=async()=>{resumedAsks++;return 'iPhone 14';};interrupted.storage.set('disney:3d-diagnostic-checkpoint',fresh.storage.get('disney:3d-diagnostic-checkpoint'));const resumedPrompt=D.create(interrupted.options,interrupted.env);await resumedPrompt.flush();assert.equal(resumedAsks,1,'An interrupted process asks on next launch');assert.equal(JSON.parse(interrupted.calls.at(-1).body).environment.model,'iPhone 14');
 const concurrent=fixture();concurrent.options.getModel=()=>'';let answer,concurrentAsks=0;concurrent.options.onModelNeeded=()=>{concurrentAsks++;return new Promise(resolve=>answer=resolve);};const waiting=D.create(concurrent.options,concurrent.env);waiting.record({name:'context-lost'});const sending=waiting.flush();await Promise.resolve();waiting.record({name:'failed'});assert.equal(await waiting.flush(),false);assert.equal(concurrentAsks,1);assert.equal(concurrent.calls.length,0,'Retain pending report while the optional question is open');answer('iPhone 16');assert(await sending);assert.equal(JSON.parse(concurrent.calls.at(-1).body).reason,'failed','Coalesced report includes the latest failure');
 const desktop=fixture();desktop.env.navigator.userAgent='Mozilla/5.0 Macintosh Chrome/132.0';desktop.options.getModel=()=>'';desktop.options.onModelNeeded=()=>{throw Error('iPhone prompt on desktop');};const pc=D.create(desktop.options,desktop.env);pc.record({name:'failed'});assert(await pc.flush());
 const html=require('node:fs').readFileSync(__dirname+'/../dist/index.html','utf8'),info=html.slice(html.indexOf('id="info-view"'),html.indexOf('id="diagnostic-model-dialog"'));assert(!info.includes('id="diagnostic-model"'),'No model field in Info/settings');assert(html.includes('id="diagnostic-model-skip"'));assert(!require('node:fs').readFileSync(__dirname+'/../dist/app.js','utf8').includes("$('diagnostic-model').addEventListener('input'"),'Typing alone must not save the optional answer');
 assert.equal(D.modelName('https://foo/?secret=1'),'');assert.equal(D.modelName('48.870500,2.779720'),'');console.log('Passed: automatic bounded reports, CSRF transport, offline persistence/retry, clean close vs interrupted launch, crash-only optional model prompt, local reuse, skipping, offline/interrupted launches, coalesced failures, iOS/Android metadata and coordinate/route/account/URL/token redaction.');
})().catch(e=>{console.error(e);process.exitCode=1;});
