<?php
require $argv[1];
function check($v,string $message): void {if(!$v)throw new Exception($message);}
$raw=['build'=>84,'reason'=>'failed','user'=>'private','route'=>[[48.8705,2.77972]],'environment'=>['browser'=>'Safari','platform'=>'iOS','version'=>'18.6','osVersion'=>'18.6.1','model'=>'iPhone 15 Pro','modelSource'=>'manual','gps'=>[48.8705,2.77972]],'events'=>[['name'=>'failed','code'=>'timeout','frames'=>1,'latlng'=>[48.8705,2.77972],'stack'=>'private','message'=>'Bad https://example.com/?gps=48.870500,2.779720&secret=123 at 48.870500,2.779720 and 48.87,2.78 user@example.com']]];
$p=disney_normalize_diagnostic($raw);check($p!==null,'Valid report');$json=json_encode($p);foreach(['private','latlng','route','gps','48.87','2.78','user@example.com','secret'] as $needle)check(strpos($json,$needle)===false,'Unexpected private field: '.$needle);check($p['environment']['model']==='iPhone 15 Pro','Model retained');check($p['environment']['osVersion']==='18.6.1','OS retained');check(disney_normalize_diagnostic(['build'=>84,'reason'=>'bad','events'=>[]])===null,'Bad event rejected');check(disney_normalize_diagnostic(['build'=>'84','reason'=>'manual','events'=>[['name'=>'manual']]])===null,'Bad build rejected');
$roof=$raw;$roof['build']=87;$roof['reason']='roof-texture-error';$roof['events']=[['name'=>'roof-texture-ready','width'=>2048,'height'=>2048,'vertices'=>23766,'bufferBytes'=>475320],['name'=>'roof-texture-error','message'=>'Roof photograph could not be loaded','uv'=>[2.78,48.87]]];$safeRoof=disney_normalize_diagnostic($roof);check($safeRoof!==null&&count($safeRoof['events'])===2,'Roof diagnostics accepted');check(!isset($safeRoof['events'][1]['uv']),'Texture coordinates excluded');
$signs=$raw;$signs['build']=88;$signs['reason']='signs-error';$signs['events']=[['name'=>'signs-ready','vertices'=>216,'width'=>1024,'height'=>864],['name'=>'signs-error','message'=>'Facade lettering shader','center'=>[48.87,2.78]]];$safeSigns=disney_normalize_diagnostic($signs);check($safeSigns!==null&&count($safeSigns['events'])===2,'Facade diagnostics accepted');check(!isset($safeSigns['events'][1]['center']),'Facade location excluded');
$letters=$raw;$letters['build']=90;$letters['reason']='roof-lettering-error';$letters['events']=[['name'=>'roof-lettering-ready','vertices'=>4857,'width'=>2048,'height'=>1536],['name'=>'roof-lettering-error','message'=>'Roof lettering shader','labels'=>['private']]];$safeLetters=disney_normalize_diagnostic($letters);check($safeLetters!==null&&count($safeLetters['events'])===2,'Roof lettering diagnostics accepted');check(!isset($safeLetters['events'][1]['labels']),'Names excluded');
$dir=sys_get_temp_dir().'/disney-diagnostic-test-'.bin2hex(random_bytes(4));mkdir($dir,0700);try{$now=time();$old=$dir.'/report-000000000000.json';file_put_contents($old,'{}');touch($old,$now-8*86400);$id=disney_store_diagnostic($dir,'synthetic-test-user',$p,$now);check(preg_match('/^[a-f0-9]{12}$/',$id)===1,'Report ID');$path=$dir.'/report-'.$id.'.json';check(is_file($path),'Stored');check((fileperms($path)&0777)===0600,'Private file');check(!is_file($old),'Old data removed');check(strpos(file_get_contents($path),'synthetic-test-user')===false,'No account in report');for($i=1;$i<20;$i++)check(disney_store_diagnostic($dir,'synthetic-test-user',$p,$now)!==null,'Below rate limit');check(disney_store_diagnostic($dir,'synthetic-test-user',$p,$now)===null,'Rate limited');check(disney_store_diagnostic($dir,'synthetic-test-user',$p,$now+3600)!==null,'Hour reset');check(disney_store_diagnostic($dir,'other-synthetic-test',$p,$now)!==null,'Independent account allowance');}finally{foreach(glob($dir.'/*') as $file)unlink($file);rmdir($dir);}
$_SERVER=['REQUEST_METHOD'=>'POST','HTTP_ORIGIN'=>'https://evil.example','HTTP_X_DISNEY_CSRF'=>'wrong'];ob_start();disney_diagnostics_response('test','csrf');$output=ob_get_clean();check(http_response_code()===403,'Cross-origin rejected');check(strpos($output,'Forbidden')!==false,'Rejected before body');
echo "Passed: strict server allowlist, redaction, model metadata, private storage, retention, rate limiting and origin/CSRF rejection.\n";
