'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),source=fs.readFileSync(__dirname+'/../dist/app.js','utf8'),elements=new Map(),clicks=new Map(),calls=[];
function element(){return {classes:new Set(),classList:{contains:k=>false,toggle(){}},open:false,dataset:{},value:'all',listeners:{},attrs:{},scrollTop:0,setAttribute(k,v){this.attrs[k]=v;},addEventListener(k,fn){this.listeners[k]=fn;},show(){this.open=true;this.modal=false;},showModal(){this.open=true;this.modal=true;},close(){this.open=false;this.listeners.close?.();}};}
const $=id=>{if(!elements.has(id))elements.set(id,element());return elements.get(id);};
const ride={id:'ride-1',name:'Test Ride',park:'Test Park',category:'attraction',node:0,latlng:[1,2]},closed={...ride,id:'ride-closed',name:'Closed Ride'},wc={...ride,id:'wc-1',name:'Toiletten'},route={order:['ride-other']};
const ctx={$,queueCheckin:null,Date,pointById:new Map([ride,closed,wc].map(r=>[r.id,r])),data:{rides:[ride,closed],toilets:[]},router:{snap:()=>({node:0,distance:0}),tree:()=>({ds:[720]})},position:null,lastFix:0,origin:[0,0],originLabel:'Parkeingang',favorites:new Set(),visited:new Set(),uninterested:new Set(),focusedRideId:null,following:true,planning:false,route,waitHistoryParent:null,objectParentDialog:null,popupWaits:new Map(),pins:{clearLayers(){clicks.clear();}},L:{divIcon:x=>x,marker:(_,options)=>({addTo(){return this;},getElement:()=>({setAttribute(){}}),on(type,fn){assert.equal(type,'click');clicks.set(options.title,fn);return this;}})},parkMatches:()=>true,nav:false,metric:m=>m+' m',minutes:m=>m/72,waitBadge:r=>`<button data-wait-history="${r.id}">35 Min.</button>`,targetAvailable:r=>r.id!==closed.id,insidePark:()=>true,
 setHeadingUp:v=>calls.push(['heading',v]),renderFollow(){},map:{panTo:(pt)=>calls.push(['pan',pt]),closePopup(){}},markShowTargets(){},updatePopupWaits(){ctx.renderMapObjectSheet();},renderObjectInfo:()=>calls.push('full-details'),renderPlaylist(){},renderShowList(){},refreshShows(){},toggleFavorite(id){if(ctx.favorites.has(id))ctx.favorites.delete(id);else ctx.favorites.add(id);},save(){},renderRides(){},visitNext:async id=>{ctx.favorites.add(id);ctx.visited.delete(id);calls.push(['next',id]);return true;},homeView(){},showMap(){},focusRideOnMap(){},openQueueCheckin(){},replan:async()=>{},complete:async()=>{}};
vm.createContext(require('./helpers/near-park.cjs')(ctx));vm.runInContext(source.slice(source.indexOf('function ageData('),source.indexOf('function childBadge(')),ctx);function use(a,b){const i=source.indexOf(a);vm.runInContext(source.slice(i,source.indexOf(b,i)),ctx);}
use('function renderMapObjectSheet(',"document.addEventListener('click',event=>{");use('function renderPins(','function markShowTargets(');
(async()=>{
 ctx.renderPins();clicks.get(ride.name)();assert($('map-object-sheet').open);assert.equal($('map-object-sheet').modal,false,'Map inspection must not make the map inert');assert.equal(ctx.focusedRideId,ride.id);assert.equal(ctx.following,false);assert.equal($('map-object-title').textContent,ride.name);assert($('map-object-travel').textContent.includes('10 Min.'));assert($('map-object-waits').innerHTML.includes('data-wait-history'));assert.equal(ctx.route,route);
 $('map-object-favorite').onclick();assert(ctx.favorites.has(ride.id));assert.equal($('map-object-favorite').textContent,'♥');
 $('map-object-more').onclick();assert(!$('map-object-sheet').open);assert($('object-dialog').open);assert.equal($('object-dialog').modal,true);$('object-close').onclick();assert($('map-object-sheet').open);assert.equal($('map-object-sheet').modal,false,'Returning from full details restores map interaction');
 ctx.openMapObjectSheet(closed.id);assert.equal($('map-object-next').disabled,false);assert.equal($('map-object-hint').textContent,'Derzeit geschlossen');assert.equal($('map-object-title').textContent,closed.name);assert.equal(ctx.route,route);
 ctx.openMapObjectSheet(wc.id);assert($('map-object-next').hidden);assert($('map-object-favorite').hidden);
 ctx.openMapObjectSheet(ride.id);assert(!$('map-object-checkin').hidden);ctx.openQueueCheckin=id=>calls.push(['checkin',id]);$('map-object-checkin').onclick();assert(calls.some(x=>Array.isArray(x)&&x[0]==='checkin'&&x[1]===ride.id));ctx.openMapObjectSheet(ride.id);await $('map-object-next').onclick();assert(! $('map-object-sheet').open);assert(ctx.favorites.has(ride.id));assert(calls.some(x=>Array.isArray(x)&&x[0]==='next'&&x[1]===ride.id));
 ctx.visited.add(ride.id);ctx.renderPins();assert(clicks.has(ride.name),'Visited ride remains a clickable map marker');ctx.openMapObjectSheet(ride.id);assert($('map-object-meta').textContent.includes('Besucht'));ctx.closeMapObjectSheet();
 ctx.uninterested.add(ride.id);ctx.openMapObjectSheet(ride.id);assert(!$('map-object-sheet').open,'Hidden objects do not reopen from old markers');assert.equal(ctx.route,route);
 ctx.uninterested.clear();ctx.visited.clear();let photoPaints=0,photoContent='';Object.defineProperty($('map-object-expanded-photos'),'innerHTML',{get:()=>photoContent,set:v=>{photoContent=v;photoPaints++;}});ctx.nearbyShowChoices=()=>[];ctx.showSchedule=()=>'<p>Schedule</p>';ctx.objectPhotos=()=>'<div>Photos</div>';ctx.objectInfo=()=>'<p>Info</p>';$('map-object-sheet').classList.contains=k=>k==='surface-fullscreen';ctx.openMapObjectSheet(ride.id);for(let i=0;i<6;i++)ctx.renderMapObjectSheet();assert.equal(photoPaints,1,'GPS redraws do not reload galleries');ctx.showSchedule=()=>'<p>New schedule</p>';ctx.renderMapObjectSheet();assert.equal(photoPaints,1,'Schedule changes preserve the gallery DOM');assert(!$('map-object-checkin').hidden,'Check-in is available in full screen');$('map-object-sheet').classList.contains=()=>false;use('function waitedTime(','function recordActualWait(');use('function renderMapObjectQueueProgress(','function renderMapObjectSheet(');
 ctx.queueCheckin={id:ride.id,startedAt:Date.now()-600000,minutes:15};ctx.openMapObjectSheet(ride.id);assert(!$('map-object-queue-actions').hidden);assert($('map-object-next').hidden);assert($('map-object-meta').textContent.includes('Du stehst hier an'));assert($('map-object-travel').textContent.startsWith('Gewartet: 10 Min.'));
 const before=$('map-object-travel').textContent;ctx.queueCheckin.startedAt-=1000;ctx.renderMapObjectQueueProgress();assert.notEqual($('map-object-travel').textContent,before,'Open waiting sheet ticks without rebuilding photos');
 ctx.openMapObjectSheet(closed.id);assert($('map-object-queue-actions').hidden);assert($('map-object-travel').textContent.includes('zu Fuß'));let finishes=0,cancels=0;$('queue-finish').onclick=()=>{finishes++;ctx.queueCheckin=null;ctx.renderMapObjectSheet();};$('queue-cancel').onclick=()=>{cancels++;ctx.queueCheckin=null;ctx.renderMapObjectSheet();};$('map-object-finish').onclick();assert.equal(finishes,0,'Different ride cannot finish the active wait');
 ctx.openMapObjectSheet(ride.id);$('map-object-cancel').onclick();assert.equal(cancels,1);assert($('map-object-queue-actions').hidden);assert($('map-object-travel').textContent.includes('zu Fuß'));
 ctx.queueCheckin={id:ride.id,startedAt:Date.now(),minutes:null};ctx.renderMapObjectSheet();assert($('map-object-travel').textContent.includes('Restzeit unbekannt'));$('map-object-finish').onclick();$('map-object-finish').onclick();assert.equal(finishes,1);assert.equal(ctx.route,route);
 console.log('Passed: waiting map sheet switches to elapsed/rest time and completion actions, ticks live, isolates other rides, cancels/restores and completes only once.');
 console.log('Passed: marker click opens non-modal compact sheet; map/route remain usable, walking/waits/favorite/next actions, full-details return, closures, WC and hidden objects.');
})().catch(e=>{console.error(e);process.exitCode=1;});
