const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/../dist/app.js','utf8'),data=JSON.parse(fs.readFileSync(__dirname+'/../dist/park-data.json'));
const cls=new Map(),style=new Map();let editing=true,layoutHeight=844,appHeight=844,resizes=0;
const ctx={fullViewportHeight:844,viewportMapHeight:0,viewportProbe:{getBoundingClientRect:()=>({height:layoutHeight})},map:{invalidateSize:()=>resizes++},originalMap:null,window:{innerHeight:844,visualViewport:{height:470,offsetTop:20,scale:1},requestAnimationFrame:fn=>fn()},document:{activeElement:{matches:()=>editing},body:{getBoundingClientRect:()=>({height:appHeight}),classList:{toggle:(k,v)=>cls.set(k,v),contains:k=>!!cls.get(k)}},documentElement:{clientHeight:844,style:{setProperty:(k,v)=>style.set(k,v)}}}};
vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf('function syncAppViewport('),source.indexOf('window.visualViewport?.addEventListener')),ctx);
ctx.syncAppViewport();assert.equal(cls.get('keyboard-open'),true);assert.equal(style.get('--app-viewport-height'),'470px');assert.equal(style.get('--app-viewport-top'),'20px');assert.equal(style.get('--map-viewport-height'),'844px','keyboard must not leave a bare strip under the map');assert.equal(style.get('--map-ui-bottom-inset'),'354px');assert.equal(resizes,1);
// A PWA can retain a short/offset visual viewport after Safari hides the keyboard.
editing=false;ctx.window.visualViewport.height=785;ctx.window.visualViewport.offsetTop=59;ctx.syncAppViewport();assert.equal(cls.get('keyboard-open'),false);assert.equal(style.get('--app-viewport-height'),'785px');assert.equal(style.get('--app-viewport-top'),'0px');assert.equal(style.get('--map-ui-bottom-inset'),'59px');assert.equal(resizes,1,'no map resize from a visual-viewport-only change');
// Regression: iPhone paint boundary at 793px while CSS canvas reports 852px.
layoutHeight=852;ctx.window.innerHeight=793;ctx.document.documentElement.clientHeight=793;ctx.window.visualViewport.height=793;ctx.window.visualViewport.offsetTop=0;ctx.syncAppViewport();assert.equal(style.get('--map-viewport-height'),'852px');assert.equal(style.get('--app-viewport-height'),'793px','menu must stay above the visible boundary even when the map is taller');assert.equal(style.get('--map-ui-bottom-inset'),'59px');assert.equal(resizes,2);
// A larger visual viewport cannot push controls outside the smaller layout viewport.
ctx.window.visualViewport.height=852;ctx.syncAppViewport();assert.equal(style.get('--app-viewport-height'),'793px');assert.equal(style.get('--map-ui-bottom-inset'),'59px');assert.equal(resizes,2);
// Browsers without VisualViewport use their visible window height.
const vv=ctx.window.visualViewport;ctx.window.visualViewport=undefined;ctx.syncAppViewport();assert.equal(style.get('--app-viewport-height'),'793px');ctx.window.visualViewport=vv;
// Installed app: an actually shorter root remains protected, regardless of CSS probe size.
cls.set('app-standalone',true);appHeight=793;ctx.window.visualViewport.height=793;ctx.syncAppViewport();assert.equal(style.get('--app-viewport-height'),'793px');assert.equal(style.get('--map-ui-bottom-inset'),'59px');
// Once the full-height root paints to the bottom, old JS viewport values must not lift the menu.
appHeight=852;ctx.syncAppViewport();assert.equal(style.get('--app-viewport-height'),'852px','standalone menu uses the full rendered root confirmed on the iPhone');assert.equal(style.get('--map-ui-bottom-inset'),'0px');assert.equal(resizes,2);
// Keyboard still lifts foreground pages, even when the installed root is full height.
editing=true;ctx.window.visualViewport.height=470;ctx.window.visualViewport.offsetTop=20;ctx.syncAppViewport();assert.equal(cls.get('keyboard-open'),true);assert.equal(style.get('--app-viewport-height'),'470px');assert.equal(style.get('--app-viewport-top'),'20px');assert.equal(style.get('--map-viewport-height'),'852px');
editing=false;ctx.window.visualViewport.height=793;ctx.window.visualViewport.offsetTop=0;ctx.syncAppViewport();assert.equal(style.get('--app-viewport-height'),'852px');assert.equal(style.get('--map-ui-bottom-inset'),'0px');
// Orientation must shrink the remembered canvas, not retain the portrait height.
layoutHeight=390;appHeight=390;ctx.window.innerHeight=390;ctx.document.documentElement.clientHeight=390;ctx.window.visualViewport.height=390;ctx.window.visualViewport.offsetTop=0;ctx.syncAppViewport();assert.equal(style.get('--map-viewport-height'),'390px');assert.equal(style.get('--app-viewport-height'),'390px');assert.equal(style.get('--map-ui-bottom-inset'),'0px');assert.equal(resizes,3);
const html=fs.readFileSync(__dirname+'/../dist/index.html','utf8');assert(html.includes('viewport-fit=cover'));assert(html.includes('name="apple-mobile-web-app-status-bar-style" content="black-translucent"'));
const css=fs.readFileSync(__dirname+'/../dist/style.css','utf8');assert(css.includes('html{height:100vh;height:100lvh;'));assert(css.includes('.map-home{height:100vh;height:100lvh;'),'the root app must cover the full viewport, not a shorter 100% containing block');
vm.runInContext(source.slice(source.indexOf('function rideSearchText('),source.indexOf('function renderRides(')),ctx);const world=data.rides.filter(r=>r.park==='Disney Adventure World');assert(world.length>1);assert(world.every(r=>ctx.rideSearchText(r).includes('adven')));assert(world.every(r=>ctx.rideSearchText(r).includes('studios')));assert(ctx.rideSearchText(data.rides.find(r=>r.name==='Adventure Isle')).includes('adven'));
console.log('Passed: keyboard, stale iOS visual viewport, full map with visible controls, window/visual mismatch, VisualViewport fallback, orientation shrink, park search.');
ctx.bottomNav={offsetHeight:73};vm.runInContext(source.slice(source.indexOf('function syncBottomNavHeight('),source.indexOf("if(typeof ResizeObserver",source.indexOf('function syncBottomNavHeight('))),ctx);ctx.syncBottomNavHeight();assert.equal(style.get('--bottom-nav-height'),'73px');ctx.bottomNav.offsetHeight=0;ctx.syncBottomNavHeight();assert.equal(style.get('--bottom-nav-height'),'73px','keyboard-hidden tabs retain their measured height');
console.log('Passed: real menu height is measured and retained while hidden by keyboard.');
