const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),RouteCore=require('../dist/routing.js');
const source=fs.readFileSync(path.join(__dirname,'../dist/app.js'),'utf8'),drawn=[],arrow={style:{}},start=[48.871,2.777],east=[48.871,2.778],west=[48.871,2.776],target={latlng:east};let rotation=0;
const ctx={finishQueueForNavigation(){},router:null,RouteCore,origin:start,position:{latlng:start},pointById:new Map([['ride-test',target]]),route:{order:['ride-test','ride-later'],legs:[{path:[start,east]},{path:[east,start,west]}]},lineLayer:{clearLayers(){drawn.length=0;}},L:{polyline(points,options){return{addTo(){drawn.push({points,options});}};}},$:()=>arrow,map:{getBearing:()=>rotation},Math};vm.createContext(ctx);
for(const [a,b]of [['function renderLines(','function updateStart('],['function bearing(','async function activateGPS('],['function renderDirection(','function updateNorth(']])vm.runInContext(source.slice(source.indexOf(a),source.indexOf(b,source.indexOf(a))),ctx);
ctx.renderLines();assert.equal(drawn.at(-1).options.color,'#245eda');assert.equal(drawn.at(-1).points,ctx.route.legs[0].path,'only the current leg is drawn');assert.equal(drawn.at(-1).options.dashArray,null);
assert.equal(drawn.length,2,'no later legs may be drawn');
ctx.renderDirection();let angle=Number(arrow.style.transform.match(/rotate\((.+)deg/)[1]);assert.ok(Math.abs(angle-90)<.01,'east should point right on north-up map');rotation=270;ctx.renderDirection();angle=Number(arrow.style.transform.match(/rotate\((.+)deg/)[1]);assert.ok(Math.abs(angle-360)<.01,'east should point up when map is oriented east');ctx.position=null;rotation=0;ctx.renderDirection();angle=Number(arrow.style.transform.match(/rotate\((.+)deg/)[1]);assert.ok(Math.abs(angle-90)<.01,'preview also uses route origin');
ctx.router={snap:()=>({node:1,distance:3}),leg:()=>({distance:50,path:[east,west]})};ctx.pointById.get('ride-test').node=2;ctx.origin=[48.872,2.778];ctx.renderLines();assert.deepEqual(Array.from(drawn.at(-1).points[0]),ctx.origin,'line starts exactly at current origin');assert.equal(drawn.length,2);assert.equal(ctx.route.legs[0].distance,53);assert.equal(ctx.route.legs[0].path.includes(start),false,'old origin path must disappear');
console.log('Passed: only current leg; current-origin start and immediate walking-path refresh; no old start; rotated direction.');
