const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../dist/app.js'),'utf8'),button={setAttribute(k,v){this[k]=v;}},storage=new Map();let rotation=0,changes=0;
const ctx={interactionPaused:()=>false,headingUp:false,original:false,heading:90,headingAt:Date.now(),userKey:'test',Date,$:()=>button,localStorage:{setItem(k,v){storage.set(k,v);}},map:{getBearing:()=>rotation,setBearing(v){rotation=v;changes++;}}};vm.createContext(ctx);
vm.runInContext(source.slice(source.indexOf('function renderOrientation('),source.indexOf('function updateNorth(')),ctx);
ctx.updateOrientation();assert.equal(changes,0);
ctx.setHeadingUp(true);assert.equal(rotation,270,'east-facing arrow must point up');assert.equal(storage.get('test:heading-up'),'true');
ctx.heading=359;ctx.updateOrientation();assert.equal(rotation,1);
ctx.heading=0;ctx.updateOrientation();assert.equal(rotation,1,'ignore tiny heading jitter across north');
ctx.heading=180;ctx.headingAt=Date.now()-16000;ctx.updateOrientation();assert.equal(rotation,1,'stale heading must not rotate');
ctx.headingAt=Date.now();ctx.original=true;ctx.updateOrientation();assert.equal(rotation,1,'original image keeps its own rotation');
ctx.original=false;ctx.updateOrientation();assert.equal(rotation,180);ctx.setHeadingUp(false);ctx.heading=90;ctx.updateOrientation();assert.equal(rotation,180);assert.equal(storage.get('test:heading-up'),'false');
console.log('Passed: heading-up alignment, north wrap, jitter threshold, stale direction, original map and mode persistence.');
let dragged=null;ctx.following=true;ctx.renderFollow=()=>{};ctx.map.on=(event,callback)=>{if(event==='dragstart')dragged=callback;};
vm.runInContext(source.split('\n').find(line=>line.startsWith("map.on('dragstart'")),ctx);
ctx.setHeadingUp(true);dragged();assert.equal(ctx.following,false);assert.equal(ctx.headingUp,false);assert.equal(storage.get('test:heading-up'),'false');
const centerCalls=[];ctx.map.setView=(...args)=>centerCalls.push(args);ctx.map.getZoom=()=>18;ctx.position={latlng:[48.871,2.777]};ctx.nav=false;ctx.headingUp=true;ctx.following=true;
const followStatement=source.match(/if\(following&&\(nav\|\|headingUp\)&&!interactionPaused\(\)\)map\.setView\([^;]+;/)[0];vm.runInContext(followStatement,ctx);
assert.deepEqual(centerCalls[0][0],ctx.position.latlng,'heading mode follows GPS without an active route');
ctx.following=false;vm.runInContext(followStatement,ctx);assert.equal(centerCalls.length,1,'manual pan is not overridden');
console.log('Passed: heading mode centers without navigation, manual drag disables heading/follow and persists.');
