'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),RouteCore=require('../dist/routing.js');
const source=fs.readFileSync(__dirname+'/../dist/app.js','utf8'),data=JSON.parse(fs.readFileSync(__dirname+'/../dist/park-data.json')),router=new RouteCore.Router(data),points=new Map([...data.rides,...data.toilets,...data.services].map(r=>[r.id,r]));
const els=new Map(),stored=new Map(),notifications=[];let distance=10000,rpcCalls=0,finishCalls=0,exits=0,pendingResolve;
const el=id=>{if(!els.has(id))els.set(id,{value:'',open:false,disabled:false,hidden:false,close(){this.open=false;},setAttribute(){},addEventListener(){}});return els.get(id);};el('ride-sort').value='distance';
const ctx={$:el,Date,RouteCore:{distance:()=>distance},localStorage:{getItem:k=>stored.get(k),setItem:(k,v)=>stored.set(k,v),removeItem:k=>stored.delete(k)},userKey:'test',toast:s=>notifications.push(s),data,router,origin:[48.87050,2.77972],originLabel:'Parkeingang',pointById:points,favorites:new Set([data.rides[0].id]),visited:new Set(),deferred:new Set(),uninterested:new Set(),planning:false,generation:0,priorityRide:null,pinnedWC:null,route:null,nav:false,position:null,lastFix:0,heading:null,headingAt:0,gpsWantNav:false,queueCheckin:null,playerDismissed:false,window:{confirm(){throw Error('Distant ride must not prompt');}},remaining:()=>data.rides.slice(0,2),finishQueueForNavigation(){finishCalls++;},exitNav(){exits++;ctx.generation++;ctx.planning=false;ctx.route=null;ctx.nav=false;},closeQueueForBrowse(){},renderRides(){},renderRoute(){},renderObjectInfo(){},renderMapObjectSheet(){},renderPins(){},renderLines(){},fitRoute(){},updateUser(){},insidePark:()=>false,save(){},map:{closePopup(){}},rpc:async()=>{rpcCalls++;return new Promise(resolve=>pendingResolve=resolve);},showNavigationMap(){throw Error('Must not start navigation');}};
vm.createContext(ctx);const use=(a,b)=>vm.runInContext(source.slice(source.indexOf(a),source.indexOf(b,source.indexOf(a))),ctx);
use('let parkDistanceMeters=', 'function minutes(');use('function rideDistances(', 'let lastRideDistancePaint=');use('async function replan(', 'function fitRoute(');use('async function visitNext(', 'async function acceptSuggestion(');use('async function navigateFacility(', "$('nav-water').onclick=");use('async function wcPause(', 'async function complete(');use('function enterNav(', 'function exitNav(');use('function toggleFavorite(', 'function renderHiddenTargets(');use('async function handleGPSPosition(', 'function refreshGPSFix(');
(async()=>{
 ctx.updateParkProximity([0,0]);assert.equal(ctx.tooFarFromPark(),false,'Exactly 10 km is allowed');distance=10000.01;ctx.updateParkProximity([0,0]);assert(ctx.tooFarFromPark());assert.equal(exits,1);assert.equal(stored.get('test:far-from-park'),'true');
 ctx.syncCatalogDistanceMode();assert.equal(el('ride-sort').value,'name');assert(el('ride-sort-distance').hidden);assert.equal(ctx.rideDistances().size,0,'No entrance-relative walking distances while distant');
 const id=data.rides[1].id;ctx.toggleFavorite(id);assert(ctx.favorites.has(id),'Favorites still work');const before=[...ctx.favorites];assert.equal(await ctx.visitNext(id),false);assert.equal(await ctx.navigateFacility(data.services[0].id),false);await ctx.wcPause();ctx.enterNav();await ctx.replan();assert.equal(rpcCalls,0);assert.equal(finishCalls,0,'Blocked actions cannot end a running wait');assert.deepEqual([...ctx.favorites],before);
 // Changing the planned start or losing the current marker cannot bypass known distance.
 ctx.origin=[48.87050,2.77972];ctx.position=null;vm.runInContext('farFromPark=false;loadParkProximity();',ctx);assert(ctx.tooFarFromPark(),'Coarse distance lock survives a reload');await ctx.replan();assert.equal(rpcCalls,0);
 distance=9999.99;ctx.updateParkProximity([0,0]);assert(!ctx.tooFarFromPark());ctx.syncCatalogDistanceMode();assert.equal(el('ride-sort').value,'distance','Preferred distance sort returns nearby');assert(!el('ride-sort-distance').disabled);assert(ctx.rideDistances().size>0);
 // An in-flight worker must not restore a route after a distant fix.
 const calculating=ctx.replan();await Promise.resolve();assert(ctx.planning);distance=15000;ctx.updateParkProximity([0,0]);pendingResolve({order:[id],legs:[],distance:1});await calculating;assert.equal(ctx.route,null);assert(!ctx.planning);
 distance=20000;const now=Date.now(),fix=at=>({timestamp:at,coords:{latitude:48.2,longitude:16.3,accuracy:10}});distance=0;ctx.updateParkProximity([0,0]);distance=20000;await ctx.handleGPSPosition(fix(now-30000));assert(!ctx.tooFarFromPark(),'Stale GPS cannot set the lock');await ctx.handleGPSPosition(fix(now));assert(ctx.tooFarFromPark());assert.match(el('gps-chip').textContent,/10 km/);distance=0;await ctx.handleGPSPosition(fix(now-1000));assert(ctx.tooFarFromPark(),'Out-of-order near fix cannot clear the lock');await ctx.handleGPSPosition(fix(now+1));assert(!ctx.tooFarFromPark());
 // This is an actual physical distance to the common park entrance, never planned origin.
 assert(RouteCore.distance([48.87050,2.77972],[48.87050,2.77972])===0);assert(RouteCore.distance([48.2082,16.3738],[48.87050,2.77972])>10000);
 console.log('Passed: strict >10 km threshold, GPS age/order, persistent coarse lock, manual-start bypass blocked, favorite edits, sort restoration, all navigation entry points and pending worker invalidation.');
})().catch(e=>{console.error(e);process.exitCode=1;});
