'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/../dist/app.js','utf8'),data=JSON.parse(fs.readFileSync(__dirname+'/../dist/park-data.json'));
const elements=new Map(),stored=new Map(),ctx={uninterested:new Set(),targetAvailable:()=>true,selectedPark:'all',appReady:true,data,userKey:'test',$:id=>{if(!elements.has(id))elements.set(id,{value:''});return elements.get(id);},localStorage:{getItem:k=>stored.get(k),setItem:(k,v)=>stored.set(k,v)},favorites:new Set(data.defaultFavorites),visited:new Set(),homeViewStates:new Map(),priorityRide:null,pinnedWC:null,route:null,nav:false,map:{closePopup(){}},save(){},renderRides(){},renderPins(){},renderNearbyShows(){},renderRoute(){},toast(){}};
vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf('function parkMatches('),source.indexOf("let activeHomeView='map'")),ctx);vm.runInContext(source.slice(source.indexOf('function remaining('),source.indexOf('function toggleFavorite(')),ctx);
(async()=>{const favorites=[...ctx.favorites];await ctx.setParkMode('Disneyland Park');assert(ctx.remaining().length>0);assert(ctx.remaining().every(r=>r.park==='Disneyland Park'));await ctx.setParkMode('Disney Adventure World');assert(ctx.remaining().every(r=>r.park==='Disney Adventure World'));assert.deepEqual([...ctx.favorites],favorites);ctx.selectedPark='all';ctx.loadParkMode();assert.equal(ctx.selectedPark,'Disney Adventure World');await ctx.setParkMode('all');assert.equal(ctx.remaining().length,favorites.length);
let paints=0,directions=0;Object.assign(ctx,{interactionPaused:()=>false,lastCompassPaint:0,heading:null,headingAt:0,updateUser(){paints++;},renderDirection(){directions++;},renderNav(){throw Error('Compass must not rebuild navigation or show UI');}});
vm.runInContext(source.slice(source.indexOf('function compassEvent('),source.indexOf('let compassAttached')),ctx);ctx.compassEvent({webkitCompassHeading:90});ctx.compassEvent({webkitCompassHeading:91});assert.equal(paints,1);ctx.lastCompassPaint=0;ctx.interactionPaused=()=>true;ctx.compassEvent({webkitCompassHeading:92});assert.equal(paints,1);assert.equal(ctx.heading,92);assert.equal(directions,1);
console.log('Passed: exclusive park targets, persisted park mode, preserved favorites, compass throttled and silent during touch.');})().catch(e=>{console.error(e);process.exitCode=1;});
