'use strict';const assert=require('node:assert/strict'),fs=require('node:fs'),data=JSON.parse(fs.readFileSync(__dirname+'/../dist/park-data.json')),{describe:describeChild}=require('../dist/child-access.js'),{candidates}=require('../server/push/decisions.cjs'),waitLib=require('../dist/wait-times.js');
const describe=ride=>describeChild(ride,{age:7,height:126});assert.equal(describeChild(data.rides[0]),null);
const ride=n=>data.rides.find(x=>x.name===n);
assert.equal(describe(ride('Indiana Jones™ and the Temple of Peril')).kind,'no');assert.match(describe(ride('Indiana Jones™ and the Temple of Peril')).text,/140/);
assert.equal(describe(ride('Avengers Assemble: Flight Force')).kind,'yes');assert.equal(describe(ride('Big Thunder Mountain')).kind,'yes');assert.match(describe(ride('Autopia')).text,/begleitet/);assert.match(describe(ride('Pirates of the Caribbean')).text,/keine Mindestgröße/);
const now=Date.parse('2026-10-05T10:00:00Z'),show=ride('Mickey’s PhilharMagic'),queue=ride('Peter Pan\'s Flight'),state={context:{at:now/1000,candidates:[{id:show.id,meters:200},{id:queue.id,meters:300,extraWalkingMinutes:2,favorite:true}]}},shows=new Map([[show.themeparksId,{status:'OPERATING',showtimes:[{startTime:'2026-10-05T12:20:00+02:00'}]}]]),waits=new Map([[`${queue.queueTimes.parkId}:${queue.queueTimes.rideId}`,{status:'OPERATING',minutes:10,baselineMinutes:40,baselineSamples:12,updatedAt:new Date(now).toISOString()}]]);
assert.equal(candidates(state,data,waits,shows,now,waitLib).length,2);assert.equal(candidates(state,data,waits,shows,now+16*60000,waitLib).length,0);
state.context.candidates[1].favorite=false;assert.equal(candidates(state,data,waits,shows,now,waitLib).length,1);shows.get(show.themeparksId).status='CLOSED';assert.equal(candidates(state,data,waits,shows,now,waitLib).length,0);
console.log('Passed: configured child height limits, accompanied Autopia, no height guess; relevant/fresh show and queue pushes, expired context, closed shows, favorites only.');
