const assert=require('node:assert/strict');const fs=require('node:fs');const {Router}=require('../dist/routing.js');
function assertNearest(router,start,stops,actual,deferred=[]){const postponed=new Set(deferred),left=new Map(stops.map(s=>[s.id,s]));let current=start,total=0;for(const id of actual.order){const active=[...left.values()].filter(s=>!postponed.has(s.id)),candidates=active.length?active:[...left.values()],ds=router.tree(current).ds,stop=left.get(id);assert.ok(candidates.some(s=>s.id===id));assert.equal(ds[stop.node],Math.min(...candidates.map(s=>ds[s.node])));total+=ds[stop.node];current=stop.node;left.delete(id);}assert.equal(left.size,0);assert.equal(actual.distance,total);assert.equal(actual.strategy,'nearest');}
let seed=11;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2**32;};
for(let iteration=0;iteration<5;iteration++){const n=7,nodes=Array.from({length:n},(_,i)=>[0,i/1000]),edges=[];for(let a=0;a<n;a++)for(let b=0;b<n;b++)if(a!==b)edges.push([a,b,Math.floor(rand()*60)+1]);const router=new Router({nodes,edges,toilets:[]}),stops=nodes.slice(1).map((_,i)=>({id:String(i+1),node:i+1})),actual=router.optimize(0,stops);assertNearest(router,0,stops,actual);assert.equal(new Set(actual.order).size,6);const skipped=[actual.order[0],actual.order[1]];assertNearest(router,0,stops,router.optimize(0,stops,skipped),skipped);}

const directed=new Router({nodes:[[0,0],[0,.001],[.001,.001]],edges:[[0,1,8],[1,2,9],[2,0,10],[0,2,50]],toilets:[]});assert.equal(directed.leg(0,2).distance,17);assert.equal(directed.leg(2,0).distance,10);assert.deepEqual(directed.optimize(0,[]).order,[]);
const park=JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'../dist/park-data.json'))),r=new Router(park),start=r.snap([48.8705,2.77972]).node;
for(const ride of park.rides){assert.ok(Number.isFinite(r.tree(start).ds[ride.node]),ride.name+' reachable');assert.ok(Number.isFinite(r.tree(ride.node).ds[start]),ride.name+' has a way back');}
const selected=park.rides.filter(x=>/Thunder|Pirates|Hyperspace|Crush|Frozen|Ratatouille/.test(x.name));const route=r.optimize(start,selected);assertNearest(r,start,selected,route);assert.equal(route.order.length,selected.length);assert.ok(route.distance>0);const next=selected[0],wc=r.toilet(start,next),wcCost=r.tree(start).ds[wc.node]+r.tree(wc.node).ds[next.node];for(const candidate of park.toilets)assert.ok(wcCost<=r.tree(start).ds[candidate.node]+r.tree(candidate.node).ds[next.node]+.001);
const pinned=r.assemble(start,[wc,...route.order.map(id=>park.rides.find(x=>x.id===id))]);assert.equal(pinned.order[0],wc.id);
const defaults=park.rides.filter(ride=>park.defaultFavorites.includes(ride.id));assert.equal(defaults.length,15);assertNearest(r,start,defaults,r.optimize(start,defaults));const all=r.optimize(start,park.rides);assertNearest(r,start,park.rides,all);assert.equal(new Set(all.order).size,park.rides.length);assert.ok(Number.isFinite(all.distance));
const deferred=[...route.order.slice(0,2)];const skipped=r.optimize(start,selected,deferred);assertNearest(r,start,selected,skipped,deferred);assert.deepEqual(new Set(skipped.order.slice(-2)),new Set(deferred));assertNearest(r,start,selected,r.optimize(start,selected,selected.map(s=>s.id)),selected.map(s=>s.id));
console.log('Passed: nearest walking distance at every stop on 5 directed graphs and real park data, postponed targets last, all-postponed recovery, directional paths, 35 reachable destinations, and minimal toilet detour.');
