'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const script=fs.readFileSync(__dirname+'/../dist/startup.js','utf8'),app=fs.readFileSync(__dirname+'/../dist/app.js','utf8');
function harness(){const nodes=new Map(),handlers=new Map(),timers=new Map();let serial=0;const doc={querySelectorAll:()=>[],getElementById:id=>{if(!nodes.has(id))nodes.set(id,{hidden:false,attrs:{},setAttribute(k,v){this.attrs[k]=v;},addEventListener(k,v){this[k]=v;}});return nodes.get(id);}};
 const ctx={document:doc,URL,Date,setTimeout:(fn,ms)=>{timers.set(++serial,{fn,ms});return serial;},clearTimeout:id=>timers.delete(id),location:{href:'https://example.test/?view=info',replace(url){this.replaced=url;}},addEventListener:(k,fn)=>handlers.set(k,fn)};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(script,ctx);return{ctx,nodes,timers,handlers};}
let h=harness();assert.equal(h.timers.size,1);h.ctx.DisneyStartup.finish();assert.equal(h.nodes.get('startup-screen').hidden,true);assert.equal(h.timers.size,0);h.ctx.DisneyStartup.fail();assert.equal(h.nodes.get('startup-screen').hidden,true,'Late failure cannot cover a usable app');
h=harness();h.timers.values().next().value.fn();assert.equal(h.nodes.get('startup-spinner').hidden,true);assert.equal(h.nodes.get('startup-retry').hidden,false);assert.equal(h.nodes.get('startup-screen').attrs['aria-busy'],'false');h.nodes.get('startup-retry').click();const url=new URL(h.ctx.location.replaced);assert(url.searchParams.has('_update'));assert.equal(url.searchParams.get('view'),'info');h.ctx.DisneyStartup.finish();assert.equal(h.nodes.get('startup-screen').hidden,true,'A slow successful start recovers from the watchdog');
h=harness();h.handlers.get('error')({target:{tagName:'SCRIPT',src:'https://example.test/vendor/leaflet.js?v=110'}});h.ctx.DisneyStartup.finish();assert.notEqual(h.nodes.get('startup-screen').hidden,true,'Missing core script cannot be hidden by partial initialization');
h=harness();h.handlers.get('error')({target:{tagName:'SCRIPT',src:'https://example.test/map-3d.js?v=110'}});h.ctx.DisneyStartup.finish();assert.equal(h.nodes.get('startup-screen').hidden,true,'3D module failure is handled separately from app startup');
const html=fs.readFileSync(__dirname+'/../dist/index.html','utf8');assert(html.indexOf('startup-screen')<html.indexOf('<main'));assert(html.includes('startup.js?v=110'));assert(html.includes('role="status">App wird geladen'));assert(html.includes('@media(prefers-reduced-motion:reduce)'));assert(app.indexOf('renderPins();updateStart();connection();refreshWaits();refreshShows();window.DisneyStartup')>0);assert(app.includes('await loadMapMode();window.DisneyStartup?.finish();startOnboarding();'));
// A hung route worker must reject, while normal replies clear the deadline.
(async()=>{let id=0;const pending=new Map(),timers=new Map(),ctx={messageId:0,pending,worker:{postMessage(message){id=message.id;}},setTimeout:(fn)=>{timers.set(1,fn);return 1;},clearTimeout:k=>timers.delete(k)};vm.createContext(ctx);vm.runInContext(app.slice(app.indexOf('function rpc('),app.indexOf('\nfunction ',app.indexOf('function rpc(')+1)),ctx);
 let promise=ctx.rpc('init',{},15000);pending.get(id).resolve(true);pending.delete(id);assert.equal(await promise,true);assert.equal(timers.size,0);promise=ctx.rpc('init',{},15000);const rejected=assert.rejects(promise,/Routenberechnung/);timers.get(1)();await rejected;assert.equal(pending.size,0);
 console.log('Passed: splash readiness, startup errors, timeout/retry, late success, optional 3D isolation and bounded worker initialization.');})().catch(e=>{console.error(e);process.exitCode=1;});
