'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{Router}=require('../dist/routing.js');
const source=fs.readFileSync(__dirname+'/../dist/app.js','utf8'),park=require('../dist/park-data.json'),open=park.rides.find(r=>r.id==='ride-555315790'),closed=park.rides.find(r=>r.id==='ride-1011446599'),show=park.rides.find(r=>r.id==='ride-animation-academy'),data={...park,rides:[open,closed,show]},router=new Router(data),els=new Map(),store=new Map(),warnings=[];let approved=false,endedQueues=0;
const $=id=>{if(!els.has(id))els.set(id,{open:false,dataset:{},setAttribute(){},close(){this.open=false;}});return els.get(id);};
const ctx={$ ,data,router,pointById:new Map([...data.rides,...data.toilets].map(r=>[r.id,r])),favorites:new Set([open.id]),visited:new Set([closed.id]),uninterested:new Set(),deferred:new Set(),priorityRide:null,pinnedWC:null,route:null,routeOrigin:null,nav:false,planning:false,generation:0,origin:[48.8705,2.77972],userKey:'test',onlyFav:false,localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},targetAvailable:r=>r?.id===open.id,parkMatches:()=>true,window:{confirm:message=>{warnings.push(message);return approved;}},finishQueueForNavigation:()=>endedQueues++,toast(){},renderRides(){},renderRoute(){},renderPins(){},renderLines(){},fitRoute(){},exitNav(){},map:{closePopup(){}},lineLayer:{clearLayers(){}},renderNearbyShows(){},focusedRideId:null,targetAvailabilityKey:'',rpc:async(type,args)=>type==='optimize'?router.optimize(args.start,args.stops,args.deferredIds):router.assemble(args.start,args.stops)};
vm.createContext(require('./helpers/near-park.cjs')(ctx));for(const [a,b] of [['function save(','function load('],['function load(','function rpc('],['function remaining(','function renderHiddenTargets('],['async function visitNext(','async function acceptSuggestion('],['async function replan(','function fitRoute('],['async function refreshTargetAvailability(','function renderNearbyShows(']]){const i=source.indexOf(a);vm.runInContext(source.slice(i,source.indexOf(b,i)),ctx);}
(async()=>{
 await ctx.replan();const previous=ctx.route;
 assert.equal(await ctx.visitNext(closed.id),false);assert(warnings.at(-1).includes('derzeit geschlossen'));assert.equal(ctx.route,previous);assert(ctx.visited.has(closed.id));assert(!ctx.favorites.has(closed.id));assert.equal(endedQueues,0,'Cancel does not end the running check-in');
 approved=true;assert(await ctx.visitNext(closed.id));assert.equal(ctx.route.order[0],closed.id);assert(!ctx.visited.has(closed.id));assert.equal(endedQueues,1);assert.equal(ctx.targetAvailable(closed),false,'Closed status remains honest');assert(!ctx.remaining().some(r=>r.id===show.id),'Other unavailable favorites do not enter automatically');
 await ctx.refreshTargetAvailability();assert.equal(ctx.priorityRide.id,closed.id);assert.equal(ctx.route.order[0],closed.id,'Live availability updates preserve the confirmed destination');
 assert.equal(JSON.parse(store.get('test')).allowUnavailableNavigation,true);ctx.priorityRide=null;ctx.load();await ctx.replan();assert.equal(ctx.route.order[0],closed.id,'Confirmed navigation survives reload');
 assert(await ctx.visitNext(show.id));assert(warnings.at(-1).includes('keine erreichbare Vorstellung'));assert.equal(ctx.route.order[0],show.id);assert(!ctx.route.order.includes(closed.id),'Previous unavailable destination loses its exception');
 const warningCount=warnings.length;assert(await ctx.visitNext(open.id));assert.equal(warnings.length,warningCount,'Available target navigates without warning');assert(!ctx.route.order.includes(show.id));assert.equal(ctx.priorityRide.allowUnavailableNavigation,false);
 console.log('Passed: closed ride and ended show require confirmation, cancel preserves route/visited/check-in, confirmed exception survives refresh/reload, next destination removes it.');
})().catch(e=>{console.error(e);process.exitCode=1;});
