'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),source=fs.readFileSync(__dirname+'/../dist/app.js','utf8'),elements=new Map(),events=new Map();
const $=id=>{if(!elements.has(id))elements.set(id,{open:false,dataset:{},listeners:{},scrollTop:0,show(){this.open=true;this.modal=false;},innerHTML:'',addEventListener(k,fn){this.listeners[k]=fn;},showModal(){this.open=true;},close(){this.open=false;this.listeners.close?.();}});return elements.get(id);};
const ride={id:'ride-test',name:'Test Ride',category:'attraction',queueTimes:{parkId:4,rideId:2}},ctx={$,objectParentDialog:null,window:{addEventListener(){}},pointById:new Map([[ride.id,ride]]),uninterested:new Set(),waitHistoryMarkup:r=>'<svg>'+r.name+'</svg>',refreshWaitHistory:r=>ctx.requested=r.id,renderMapObjectSheet:()=>ctx.restored='map',renderObjectInfo:()=>ctx.restored='object',renderPlaylist:()=>ctx.restored='playlist',document:{addEventListener:(k,fn)=>events.set(k,fn)},openObjectInfo:()=>{throw Error('Statistics click must not open object info');},waitInfo:()=>({kind:'open',text:'35 Min. Wartezeit',detail:'Source'}),singleRiderInfo:()=>null,esc:String};
vm.createContext(ctx);function use(a,b){const i=source.indexOf(a);vm.runInContext(source.slice(i,source.indexOf(b,i)),ctx);}
use('let waitHistoryParent=','let objectParentDialog=');use("document.addEventListener('click',event=>{\n const historyView=",'function childBadge(');use('function waitBadge(','function ratingBadge(');
assert(ctx.waitBadge(ride).includes('data-wait-history="ride-test"'),'The shared wait badge used in navigation/popups/lists/details is clickable');
$('object-dialog').open=true;events.get('click')({target:{closest:s=>s==='[data-wait-history]'?{dataset:{waitHistory:ride.id}}:null}});assert($('wait-history-dialog').open);assert(!$('object-dialog').open);assert.equal(ctx.requested,ride.id);assert($('wait-history-content').innerHTML.includes(ride.name));
$('wait-history-close').onclick();assert($('object-dialog').open);assert.equal(ctx.restored,'object');$('object-dialog').open=false;
$('route-playlist').open=true;ctx.openWaitHistory(ride.id);assert(!$('route-playlist').open);$('wait-history-dialog').close();assert($('route-playlist').open);assert.equal(ctx.restored,'playlist');
$('route-playlist').open=false;$('map-object-sheet').open=true;ctx.openWaitHistory(ride.id);assert(!$('map-object-sheet').open);$('wait-history-dialog').close();assert($('map-object-sheet').open);assert.equal($('map-object-sheet').modal,false);assert.equal(ctx.restored,'map');
ctx.uninterested.add(ride.id);ctx.openWaitHistory(ride.id);assert(!$('wait-history-dialog').open,'Hidden rides cannot open from stale elements');
console.log('Passed: shared wait badge opens statistics, details/playlist return, current ride is loaded, and hidden-target guard.');
