'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/../dist/app.js','utf8');
let now=Date.parse('2026-10-06T12:00:00+02:00');class Clock extends Date{static now(){return now;}}
const ride={id:'ride-test',category:'attraction',queueTimes:{parkId:4,rideId:2}},other={id:'ride-other',category:'attraction',queueTimes:{parkId:4,rideId:8}},dialog={open:true,dataset:{rideId:ride.id}},renders=[];
let response,fail=false,requests=[];
const ctx={esc:s=>String(s),Date:Clock,Intl,Map,Number,navigator:{onLine:true},singleRiderIds:{'4:2':7306},location:{pathname:'/files/.internal/Disney/'},AbortController,setTimeout:()=>1,clearTimeout(){},$:()=>dialog,renderWaitHistoryDialog:()=>renders.push(dialog.dataset.rideId),fetch:async(url,options)=>{requests.push(url);assert.equal(options.cache,'no-store');assert.equal(options.redirect,'error');if(fail)throw Error('network');return {ok:true,json:async()=>response};}};
vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf('const waitHistories='),source.indexOf('let waitHistoryParent='))+'\nthis.setHistory=(r,record)=>waitHistories.set(waitHistoryKey(r),{view:"today",...record});',ctx);
const at=time=>Date.parse('2026-10-06T'+time+':00+02:00')/1000;
const payload={date:'2026-10-06',fetchedAt:now/1000,stale:false,series:[{id:2,samples:[{at:at('08:30'),minutes:0},{at:at('08:35'),minutes:30},{at:at('09:00'),minutes:60},{at:at('13:00'),minutes:500},{at:at('09:05'),minutes:-1},{at:at('08:35')-86400,minutes:600}]},{id:7306,samples:[{at:at('08:30'),minutes:5},{at:at('08:35'),minutes:15}]}]};
ctx.setHistory(ride,{payload});let html=ctx.waitHistoryMarkup(ride);
assert(html.includes('5 Datenpunkte'));assert(html.includes('Jetzt 12:00'));assert(!html.includes('NaN'));assert(html.includes('Ø zeitgewichtet'));assert(html.includes('>30<small> Min.'));assert(html.includes('>60<small> Min.'));assert(html.includes('Single Rider'));assert.equal((html.match(/<polyline/g)||[]).length,3,'Long collection gap breaks the regular line');assert.equal((html.match(/<circle/g)||[]).length,5,'Only today, valid and not-future measurements');assert(!html.includes('500 Min.'));assert.equal(ctx.waitHistoryMarkup({...ride,category:'show'}),'');assert.equal(ctx.waitHistoryMarkup({id:'wc-test'}),'');assert.match(ctx.waitHistoryMarkup({id:'ride-no-feed'}),/keine Wartezeiten veröffentlicht/);
ctx.setHistory(ride,{payload:{...payload,series:[{id:2,samples:[{at:at('08:30'),until:at('09:30'),minutes:10},{at:at('09:30'),until:at('09:40'),minutes:80}]}]}});assert(ctx.waitHistoryMarkup(ride).includes('>20<small> Min.'),'Mean is duration weighted, not biased by number of value changes');
ctx.setHistory(ride,{payload:{...payload,series:[{...payload.series[0],meanMinutes:null}]}});assert(ctx.waitHistoryMarkup(ride).includes('>—<small> Min.'),'No confirmed in-window observations means no today average');
ctx.setHistory(ride,{payload:{...payload,series:[{...payload.series[0],meanMinutes:42}]}});assert(ctx.waitHistoryMarkup(ride).includes('>42<small> Min.'),'Today average uses the server opening-window calculation');
ctx.setHistory(ride,{payload:{...payload,series:[]}});assert.match(ctx.waitHistoryMarkup(ride),/noch keine Messwerte/);
ctx.setHistory(ride,{view:'average',payload:{...payload,typical:{series:[{id:2,days:2,range:{startMinute:480,endMinute:1320},samples:[{minute:510,minutes:37.5,days:2,observedSeconds:1800},{minute:540,minutes:20,days:1,observedSeconds:900}]}]}}});html=ctx.waitHistoryMarkup(ride);assert(html.includes('15-Minuten-Mittel'));assert(html.includes('2 erfasste Tage'));assert(html.includes('37,5'));assert.equal((html.match(/<polyline/g)||[]).length,2,'Missing 15-minute bucket is a gap');assert(html.includes('08:30–08:45'));assert(html.includes('Messwerte bisher ab 08:30'));assert(html.includes('08:00</text>'));assert(html.includes('22:00</text>'),'Axis uses the entire allowed window, not just the sample range');
ctx.setHistory(ride,{payload,error:true});assert.match(ctx.waitHistoryMarkup(ride),/Letzter Stand/);assert(ctx.waitHistoryMarkup(ride).includes('5 Datenpunkte'));
(async()=>{
 response=payload;ctx.setHistory(ride,{at:0});await ctx.refreshWaitHistory(ride);assert(requests[0].includes('&park=4&ride=2&single=7306'));assert.equal(renders.length,1);await ctx.refreshWaitHistory(ride);assert.equal(requests.length,1,'Repeated renders do not refetch for a minute');
 now+=60000;fail=true;await ctx.refreshWaitHistory(ride);assert.match(ctx.waitHistoryMarkup(ride),/Letzter Stand/);assert(ctx.waitHistoryMarkup(ride).includes('5 Datenpunkte'),'Failed refresh retains cached observations');
 fail=false;response={...payload,date:'2026-10-05'};await ctx.refreshWaitHistory(other);assert.match(ctx.waitHistoryMarkup(other),/momentan nicht verfügbar/);assert.equal(renders.length,2,'Finishing another ride request does not repaint the current dialog');
 now=Date.parse('2026-10-06T22:30:00Z');assert.equal(ctx.waitHistoryDay(),'2026-10-07','Paris midnight invalidates yesterday cache');assert(!ctx.waitHistoryMarkup(ride).includes('5 Datenpunkte'));
 console.log('Passed: real zero, daily min/mean/max, independent Single Rider, Paris date/future/invalid filters, gap breaks, unknown/empty/error states, request limits, cached refresh failure and dialog race.');
})().catch(e=>{console.error(e);process.exitCode=1;});
