Listen 8080
ServerName abetterdisneylandparisapp.weletapi.com
ServerTokens Prod
ServerSignature Off
PidFile /tmp/apache2/apache2.pid
Mutex file:/tmp/apache2 default
<VirtualHost *:8080>
    DocumentRoot /var/www/html
    ServerName abetterdisneylandparisapp.weletapi.com
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
    LimitRequestBody 32768
    <Directory /var/www/html>
        Options -Indexes -Includes -ExecCGI
        AllowOverride None
        Require all granted
        DirectoryIndex index.php
        RewriteEngine On
        RewriteRule ^index\.php$ - [END]
        RewriteRule ^$ index.php [END]
        RewriteRule ^(.+)$ index.php?asset=$1 [END,QSA,B]
    </Directory>
    Header always set X-Content-Type-Options "nosniff"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
    Header always set Strict-Transport-Security "max-age=15552000"
    Header always set Permissions-Policy "geolocation=(self), accelerometer=(self), gyroscope=(self), magnetometer=(self), screen-wake-lock=(self), microphone=(), camera=(), payment=()"
    Header always set Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://tile.openstreetmap.org; connect-src 'self'; worker-src 'self'; manifest-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'self'"
</VirtualHost>
